### ISSUE TITLE
Lacking PWA Features

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#109]
Google LightHouse Reports .
Web is lacking PWA Features.
Improve any of the suggestion by attached Lighthouse report and send the PR for the same 👍 .

![screencapture-googlechrome-github-io-lighthouse-viewer-2018-11-11-01_57_23](https://user-images.githubusercontent.com/13464678/48305693-70aa7400-e555-11e8-9afd-9e2cc9801b6e.png)

Apart from that you can add google lighthouse chrome extension to generate live report, this is the sample report generated on 17 oct 2018.

**Comment by CDharmateja** [comment]
Service worker and HTTP/2 both need https in order to work. Let's Encrypt website provides free SSL/TLS certificates. We can use it for the website.

**Comment by CDharmateja** [comment]
Can I lazyload images to improve performance?

**Comment by divyanshu-rawat** [comment]
@CDharmateja sorry for late response, if you want to lazy-load images, then you can do so.
