### ISSUE TITLE
Login/Logout BUG

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#148]
**Describe the bug**
Login/Logout works fine first time, but when user again tries to login it shows err.

**To Reproduce**
1. Go to studentLogin
2. Log userself in.
3. then Log yourself out.
4. then again head over to studentLogin, it will throw an err.

**Expected behavior**
Once user is logged in and logout himself/herself out, then if user tries to log himself/herself in again that it should allow use to log him/her in.

**Screenshots**
![screencast](https://user-images.githubusercontent.com/13464678/47606086-f0e8b980-da2c-11e8-91ae-d19d4ae8ec03.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
To debug head over to privateRoutes.js, some bug is there, that needs to be debugged https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/master/src/ignitus-Routes/privateRoute.js

**Comment by jonathanjwatson** [comment]
<img width="1440" alt="screen shot 2018-10-28 at 11 44 00 am" src="https://user-images.githubusercontent.com/9114299/47618211-d4896300-daa6-11e8-885c-be2c9025e840.png">

**Comment by divyanshu-rawat** [comment]
@jonathanjwatson that is the bug.
