### ISSUE TITLE
CSS for error in form UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#218]
**Is your feature request related to a problem? Please describe.**
We need to add the css for the errors in the form UI.

**Describe the solution you'd like**
Implementation of attached UI for errors. 

**Additional context**
Refer [UI Toolkit](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=0%3A1) for User-Interface and other style-related issues.

**Expected-Interface**
![screenshot from 2018-12-31 23-51-24](https://user-images.githubusercontent.com/26546816/50565654-0fce3980-0d57-11e9-9245-5120b0778388.png)

**Comment by sweezy793** [comment]
@Paarmita but for this don't we need validation messages from server side ?

**Comment by arc9693** [comment]
I would like to work on this issue.

**Comment by divyanshu-rawat** [comment]
@sweezy793 are you still working on this? Yes but server side validations are already there, if you will register via `username` that already exist it will throw an error that username already exists, but as of now `error` is shown like this
![screenshot 2019-02-26 at 11 07 56 am](https://user-images.githubusercontent.com/13464678/53404849-cb59c580-39b6-11e9-8399-92f00b0561ba.png)

So this issue is about improving the UI of how error is shown, let me know if you have any further Questions 👍

**Comment by divyanshu-rawat** [comment]
@arc9693 you can go ahead 👍

**Comment by pradnyasd** [comment]
Can I work on this issue?

**Comment by Paarmita** [comment]
@arc9693 @sweezy793 Are you working on this one or I could assign it to @pradnyasd ?

**Comment by sweezy793** [comment]
@Paarmita I'm not working in it, you can assign it him

**Comment by arc9693** [comment]
@Paarmita I am working on it as well

**Comment by arc9693** [comment]
@divyanshu-rawat gave me a thumbs up to go ahead with this.

**Comment by Paarmita** [comment]
@arc9693 Cool! GO ahead and make a PR. 
@pradnyasd You can take up some other issue.

**Comment by arc9693** [comment]
@Paarmita can you please put the label 'gssoc19' on this issue?

**Comment by divyanshu-rawat** [comment]
I believe validation is buggy, It would be great if someone can have a look on it, I am keeping this issue open.

Current validation to check email validity also seems to be too complex.
Have a look here. https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-StudentSignUp/Components/Signup.js.

I believe we can simply use `regex` to check email `format`.
Something like this -` const regExp = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;`

**Comment by PravallikaKura** [comment]
I and my teammate @HarshiniKarumuri want to work on this project for RGSoC. We have experience in HTML, CSS, JavaScript,React.We would like to work on this issue.Please guide us through this.
