### ISSUE TITLE
Transforming an SVG logo on a React Component

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#228]
**Is your feature request related to a problem? Please describe.**
As we see the navbar, on the blue background the logo is not visible, because logo color is same as the background one. 

**Describe the solution you'd like**
As the navbar class changes the SVG logo color must changes accordingly like for transparent and white background- it should be Hex # 000066 and for white background- # FFFFFF. We need to pass props in the react component of the SVG logo to see this behavior.

**Describe alternatives you've considered**
None till so far.

**Additional context**
Helpful: 

- https://blog.prototypr.io/svg-illustrations-as-react-components-f0e7be304eb6
- https://open.nytimes.com/flexible-icons-with-react-svg-973f310e6382

**Comment by vinodh99** [comment]
I would like to look into this issue Paarmita.

**Comment by divyanshu-rawat** [comment]
Thanks @vindu939 please go ahead 👍 .

**Comment by mpriyadarshini** [comment]
Is this issue still open?

**Comment by Paarmita** [comment]
@mpriyadarshini Yes, feel free to create a PR for it.

**Comment by CDharmateja** [comment]
I would like to work on this.

**Comment by Paarmita** [comment]
Yes sure @CDharmateja You can take up if @mpriyadarshini is not working on it.

**Comment by lazycipher** [comment]
Hello @CDharmateja @mpriyadarshini,
Any updates on this issue?

**Comment by lazycipher** [comment]
@Paarmita, Should I work on this?
