### ISSUE TITLE
Add Forgot password functionality

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#299]
We can add a new feature to reset the password, in case the user has already signed in and forgot the password.

**Comment by arc9693** [comment]
Hey @Paarmita  I would like to work on this issue. It would be helpful if you can guide me through the flow. Is there any function on the server side to support this?

**Comment by Paarmita** [comment]
@arc9693 No, at present there is no functionality from server side.

**Comment by divyanshu-rawat** [comment]
hey @arc9693 I will implement it soon not getting much time these days 😅.

**Comment by arc9693** [comment]
@divyanshu-rawat  Sure. I can work on it on the server-side. I have my exams currently, but I will send a PR soon. I would recommend opening an issue on the rest API repo as well.

**Comment by divyanshu-rawat** [comment]
@arc9693 go ahead 👍
