### ISSUE TITLE
UI of navigation bar in Sign in / Sign up page

### ISSUE THREAD

**Issue by CDharmateja** [Ignitus/Ignitus-client#316]
**Describe the bug**
The background of navigation bar of login/signup page at certain width(for me between 1000-1100px) is white including the links.

**To Reproduce**
1. Go to http://www.ignitus.org/Login 
2. Open dev tools(Ctrl + Shift + i)
3. Resize width
4. Bug will be seen somewhere between 1000 to 1200 px width 

**Expected behavior**
Navigation bar either show hamburger icon without links (or) show the links in blue background.

**Screenshots**
![Screenshot from 2019-05-11 21-39-01](https://user-images.githubusercontent.com/29755510/57572284-a8777300-7435-11e9-8f45-ad568ea6bd1b.png)

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Brave
 - Version: Chromium 72

**Comment by Paarmita** [comment]
@CDharmateja Thanks for pointing out. Would you like to work on it?

**Comment by CDharmateja** [comment]
@Paarmita  Yeah I will work on it
