### ISSUE TITLE
Migration to react-hooks. ★

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#395]
Migration of existing `ES6` based class components to **react-hooks**. ★

Hooks let you use state and other React features without writing a class.

**Reference:**  https://reactjs.org/docs/hooks-overview.html

**Comment by divyanshu-rawat** [comment]
#474  Migrates Team & Testimonial Component, Navigation Component is still pending. 👍

**Comment by steric85** [comment]
Hey! I am a GSSoC'20 participant. I'd like to work on this.

**Comment by divyanshu-rawat** [comment]
@steric85 sure go ahead 👍 , I did the migration of most of the components you can try with the remaining ones.

**Comment by steric85** [comment]
Thank you @divyanshu-rawat . I'll start migrating right away.

**Comment by dibakar95** [comment]
Hi, @divyanshu-rawat is this issue fixed. If not, I can give it a go. 
- Participant GSsoC20

**Comment by divyanshu-rawat** [comment]
@dibakar95 Hey, thanks for your interest, 

Some components are still using class based implementation instead of react-hooks I don't exactly what components you can search for  something like `extends`  in the code base in your editor, to see which components are extending parent react class React.Component or Component if your import is like this import { Component } from 'react'. see and replce them hooks, ping me if you struck. 

Good Luck ☘️
