### ISSUE TITLE
Careers page design 🎨

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#396]
**Is your feature request related to a problem? Please describe.**
Careers page design 🎨

**Describe the solution you'd like**
![Careers- Job](https://user-images.githubusercontent.com/13464678/69923284-f3c1a380-14a3-11ea-8ae2-03ac412b2e2e.png)

**Comment by Paarmita** [comment]
The Career page can be divided into two parts, something like this.

![Group 24](https://user-images.githubusercontent.com/26546816/75616782-0f495280-5b56-11ea-87cc-897c4fe1eb64.png)

**Comment by divyanshu-rawat** [comment]
**FYI:** This issue is already assigned to @kamal-kaur04  as of now :)

**Comment by kamal-kaur04** [comment]
Hey, @divyanshu-rawat Can you provide these images for careers page?

**Comment by divyanshu-rawat** [comment]
hey @kamal-kaur04 Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8)  for User-Interface, Images and other styles-related issue.

**Comment by kamal-kaur04** [comment]
@divyanshu-rawat I have some queries regarding the flow of source code. Should I ask you here or can ping on slack?

**Comment by divyanshu-rawat** [comment]
@kamal-kaur04 ping me on slack 👍

**Comment by Meghana-12** [comment]
I would like to work on this issue.
