### ISSUE TITLE
Job description page design 🎨.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#397]
**Is your feature request related to a problem? Please describe.**
Job description page design 🎨.

**Describe the solution you'd like**
Similar to the attached screenshot ★.

**Additional context**
Add any other context or screenshots about the feature request here. 📸

![Job Description Apply](https://user-images.githubusercontent.com/13464678/69923329-41d6a700-14a4-11ea-8d73-b639a642b223.png)

**Comment by divyanshu-rawat** [comment]
Job description page can be divided into `two` parts, something like this.

![job_description](https://user-images.githubusercontent.com/13464678/75616572-d78cdb80-5b52-11ea-900d-c0e3da69f26f.png)


One can pick either the `first` part or other can pick the `second` part.

**Comment by kritika12298** [comment]
Hello, I am Kritika Gupta and am looking forward to apply for Job Description Page. If no one is working on this issue then can you assign it to me?

**Comment by yj2303** [comment]
I would like to work on this issue as part of GSSOC'20
