### ISSUE TITLE
Job confirmation page design 🎨.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#398]
**Is your feature request related to a problem? Please describe.**
Job confirmation pasge design ★

**Describe the solution you'd like**
Similar to the attached screenshot.

**Describe alternatives you've considered**
👨‍💻

**Additional context**

![Job Apply Confirmation](https://user-images.githubusercontent.com/13464678/69923450-3768dd00-14a5-11ea-90d4-9adb867f253f.png)

**Comment by Paarmita** [comment]
The job confirmation page can be divided into two parts, something like this.

![Group 23 (1)](https://user-images.githubusercontent.com/26546816/75616736-7286b500-5b55-11ea-90eb-83f558174615.png)


One can pick either the first part or others can pick the second part.
The second part is mostly about creating a confirmation card.

**Comment by divyanshu-rawat** [comment]
The job description page can be divided into two parts, something like this. please refer. #545. #544 to work on this.

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue as part of GSSOC'20

**Comment by divyanshu-rawat** [comment]
please go ahead @ashishnagpal2498 👍
