### ISSUE TITLE
Bundle size optimisation.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#399]
We are relying on may external modules, which in the end increase the bundle size.
for instance - Imagine a use case of using **lodash**, like in order to _concat 2 arrays_ we can make use of fn offered by **lodash** know as` _.concat(array, [values])`, but if we import **lodash** just for doing this, it doesn't make sense and will can increase the **downloading** time of the application by some `ms`.

> Task: 

Look for such instances for different **npm** packages in the codebase, it can also be some animation/transition that can be achieved by making use of **css**, instead of importing an **npm** package.
Cost of adding any **npm** package can be seen here, https://bundlephobia.com/

You can find list of all `lodash` methods here as well, https://github.com/lodash/lodash

**Comment by abhu-A-J** [comment]
@divyanshu-rawat I'll take this one. Functions I'm planning to replace are:
1. isEmpty 
2. isObject 
3. isString
4. isEqual

I could find only these as of now, I'll update others as well if I find them

**Comment by divyanshu-rawat** [comment]
Thanks sounds good to me 😀
