### ISSUE TITLE
 Bootstrap 4 => Pure CSS

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#403]
**Is your feature request related to a problem? Please describe.**
I think we should remove our project dependency on Bootstrap 4, as it also utilizes flex based layout, and most of the times we end up not using all the capabilities offered by bootstrap.

**Describe the solution you'd like**
When have also integrated Material Design in the dashboard, so I don't think it makes sense to make use of BS4 and MD in the same project, I would rather like to remove both and rely on https://emotion.sh/docs/styled

**Describe alternatives you've considered**
https://emotion.sh/docs/styled

**Additional context**
Will migrate the dependency step by step, small PR'S with removal of BS4 classes replaced with custom-css will be quite helpful.

> Why #no-sass?

* BEM syntax is annoying.
* Bloated css output, nested selector overload, unused css on a given page.
* Needed critical css.
* Sass compilation is slow due to a few factors (theming, static assets etc). 
* Need to keep components consistent. 
* Not easy to update many components. 
* Performance is critical. 
* We want a framework which will be relatively future proof. 
* We need a great developer exp.

> Why Emotion?

* Popular CSS-in-JS framework.
* Excellent performance. 
* Don't need to clutter JSX with styled components.
* Easiest migration path out of all CSS-in-JS frameworks.
* Supports composition, nested selectors and global styles. 
* Supports server side rendering.
* Plays nice with legacy sass components Cons.

So, I am adding RGSoC label to this issue as well, everyone can independently work on migration of components and please when you take up this issue then let us know via commenting that which component you are planning to migrate, if not a component them which files. ;)
If you have further Questions ping me anytime in Ignitus/GSSOC slack.

Here are the list of components that are migrated till so far to `emotion` in mentioned pull request.
#524

1 - ignitus-WhatWeDo
2 - ignitus-Contributors
3 - ignitus-CoreTeam
4 - ignitus-Partners

and some other files.
cc @debck , @gittysachin please keep this in mind, and we will keep on updating this issue as more and more components keep on migrating 👍

**Comment by divyanshu-rawat** [comment]
#478 Addresses similar problem. ⚡️

**Comment by divyanshu-rawat** [comment]
#476 is also related.

**Comment by suraj111999** [comment]
I want to do work on this issue

**Comment by yj2303** [comment]
I would like to work on this issue.

**Comment by abhu-A-J** [comment]
@divyanshu-rawat Can I refactor the `footer` from `BS4` to `custom CSS` on this issue. Also I just finished learning `CSS-in-JS` using Emotion and I'll like to include that while working on this . So may I try this out, please?

**Comment by divyanshu-rawat** [comment]
cool @abhu-A-J  go ahead, I would also like to highlight one learning opportunity for you to learn hooks & passing props to emotion.
If you will use emotion then the behaviour attached in the gif, needs to be in emotion way.
It would be great if you can do something like this on smaller screen, see the arrow `collapsing & expanding` here http://www.ignitus.org/interface.

We can hide/show the content in the same way once emotion is introduced in footer, here is the logic https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx#L23 for this implementation http://www.ignitus.org/interface.

![footer](https://user-images.githubusercontent.com/13464678/77826000-1049b180-710d-11ea-9e74-d92b4d9133d7.gif)


Nevertheless priority is to convert footer => pure css, emotion , expansion/collapsing emotion is next priority. feel free to do it in any way as you like.


Thanks :) , ping me if you need any help or have any question. 

Good Luck ☘️

**Comment by divyanshu-rawat** [comment]
@yj2303 which component would you like to convert into pure css? :)

**Comment by yj2303** [comment]
I am using ** purecss-sass** to fix this problem.

**Comment by divyanshu-rawat** [comment]
@yj2303 yes but which components due you to convert into pure css?

**Comment by divyanshu-rawat** [comment]
Removed bootstrap 4
