### ISSUE TITLE
LazyLoad Images to enhance perf.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#453]
**Is your feature request related to a problem? Please describe.**
It would be great if can lazyLoad images to enhance performance. ★

**Describe the solution you'd like**
https://www.npmjs.com/package/react-lazyload

**Comment by Saumya29** [comment]
Can I take this up?

**Comment by divyanshu-rawat** [comment]
Sure :) . feel free to do so 🎉
