### ISSUE TITLE
Add support for username durning registration.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#454]
**Is your feature request related to a problem? Please describe.**
Currently during user registration we ask for `email` followed by `password`.

**Describe the solution you'd like**
It would be great if we can ask for username as well, so that we can show it in the header once user logs in.

**Describe alternatives you've considered**
None as of now.

**Additional context**
If you want you can also update server-side to support the username.
Here is the model for user.
https://github.com/Ignitus/Ignitus-rest-api/blob/master/api/Models/user.js

Here is the route that accepts user registration object. 
https://github.com/Ignitus/Ignitus-rest-api/blob/master/api/Controllers/user.js

**Comment by ashutosh97** [comment]
I would like to work on it.

**Comment by ashutosh97** [comment]
@divyanshu-rawat I am opening an issue on backend repo for the same.

**Comment by Marvin9** [comment]
Any update on this issue?

**Comment by divyanshu-rawat** [comment]
@Marvin9 due to major api changes I had to close the old PR, it's not a priority now.

**Comment by Paarmita** [comment]
We have planned not to add the username support, so closing this.
