### ISSUE TITLE
Introduce Styled Components 🎨

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#476]
**Is your feature request related to a problem? Please describe.**
Once we are done with removal of BS4 and MD from the project, we plan to migrate to https://emotion.sh/docs/styled.

**Comment by divyanshu-rawat** [comment]
#403 All addresses the similar concern. ✔️

**Comment by divyanshu-rawat** [comment]
#478  already did the migration to emotion from BS4 => Pure CSS => Emotion. 👩‍🎤but issue is still not finished as we need to do it for other components as well.

**Comment by divyanshu-rawat** [comment]
Before working on this issue please read #403  description :)

**Comment by marylicious** [comment]
I want to work on this as part of GSSOC

**Comment by gittysachin** [comment]
Sure @marylicious, go ahead 👍

**Comment by divyanshu-rawat** [comment]
Hello @marylicious first of all thanks for your interest in the ticket :) , would like to let you know before you proceed `styled components `are already been introduced, what you need to do is to migrate any component that is not yet migrated #478 adds [emotion](https://emotion.sh/docs/styled) to the project, some this issue can be divided into 2 parts.


1 - Migrate Bootstrap 4 based component to Pure CSS.
2 - Migrate Pure CSS to styled components i.e - [emotion](https://emotion.sh/docs/styled) in our case.


Emotion is pure css only difference being written in terms of JS.
Let me know if you have any questions, its not that easy issue to get started :)

**Comment by divyanshu-rawat** [comment]
Migrated entire codebase to Emotion styled CSS
