### ISSUE TITLE
Migration prop-Types => TS ★

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#477]
**Is your feature request related to a problem? Please describe.**
We also plan to migrate our Type checking capabilities to TS.

**Describe the solution you'd like**
Migration to TS ★

**Describe alternatives you've considered**
Flow seems good but still TS offer more capabilities.

**Additional context**
https://www.typescriptlang.org/

So, I am adding `RGSoC` label to this issue as well, everyone can independently work on migration of components and please when you take up this issue then let us know via commenting that which component you are planning to migrate, if not  a component them which files. ;)
If you have further Questions ping me anytime in Ignitus/GSSOC slack.

Here are the list of components that are migrated till so far to `TypeScript` in mentioned pull request.
https://github.com/Ignitus/Ignitus-client/pull/524

1 - `ignitus-About`
2 - `ignitus-Contributors`
3 - `ignitus-CoreTeam`
4 - `ignitus-Partners`
5 - `ignitus-Team`

and some other files.
cc @debck , @gittysachin please keep this in mind, and we will keep on updating this issue as more and more components keep on migrating 👍

**Comment by divyanshu-rawat** [comment]
1st step is to convert any file to TS file, and then replicate the same for other files as well 👍

**Comment by steric85** [comment]
Hey! I am a GSSoC'20 participant. I'd like to work on this.

**Comment by divyanshu-rawat** [comment]
sure go ahead 👍 , #524 does migration from some components, feel free to pick some other component, or wait until tom. I will compile here a list of components that I think are in need of migration :)

**Comment by steric85** [comment]
Sure, thanks a lot!

**Comment by steric85** [comment]
Hey @divyanshu-rawat 
I started with the common-auth-student-prof folder. Could you please review the changes in #548  to know if I'm going in the right direction?

**Comment by divyanshu-rawat** [comment]
Sure will do thanks :) 😊

**Comment by divyanshu-rawat** [comment]
once @steric85 is done migrating some components, they we are taking this issue out of `gssoc20` to `rgsoc20`.

**Comment by toshihidetagami** [comment]
Hi! This is cool project so I want to take part.
I picked `ignitus-Introduction` and just made a pull request.

**Comment by divyanshu-rawat** [comment]
Thanks @toshihidetagami for your Interest, you can also join our [slack](https://bit.ly/JoinIgnitusSlack) if you are interested to contribute further :).

**Comment by toshihidetagami** [comment]
@divyanshu-rawat Thanks for the invitation. I will definitely join!

**Comment by aysp-99** [comment]
Hi! I'd like to work on `ignitus-GetStarted`, sub folder of `ignitus-HomePage`. But `GSSoC` label was removed so can I still work on it?

**Comment by gittysachin** [comment]
@aysp-99 you can check other issues that have GSSoC labeled issues. We've specifically labeled this issue for RGSoC participants. Thanks :)

**Comment by divyanshu-rawat** [comment]
@aysp-99 you can go ahead 👍 , @gittysachin the problem is that new all the new PRS, that we have merged have JS written on them instead of TS leaving lot of work for migration, so even if @aysp-99 will work on migrating some components new contributors will add more JS files which Implies we always have to migrate to TS leaving migration to TS as `IN-PROGRESS` task always, nevertheless after sometime we will change our contribution guidelines that we will accept PRS written in TS only.

**Comment by aysp-99** [comment]
Sure. Thanks :)

**Comment by gittysachin** [comment]
Thanks @divyanshu-rawat, I'll keep that in mind. @aysp-99 please go ahead :+1:

**Comment by aysp-99** [comment]
Can I work on `testimonial` component or any other component that you'd suggest me to work on?

**Comment by Paarmita** [comment]
@aysp-99 We want to change the UI for testimonials, so if you want to migrate the component then you also need to change the UI, are you willing to work on that as well?

**Comment by aysp-99** [comment]
@Paarmita Yes, Sure. I shall do that. :)

**Comment by Paarmita** [comment]
@aysp-99 Okay, I will assign you the issue.

**Comment by Marvin9** [comment]
Migration is completed in v6.2.0 🎉 Can we close this one?
