### ISSUE TITLE
Migration FontAwesome => SVG ★

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#479]
**Is your feature request related to a problem? Please describe.**
Migration FontAwesome => SVG ★

**Describe the solution you'd like**
 It doesn't make sense to increase the bundle size in production but loading additional library FontAwesome its better to create a component that will take `SVG` and render it.

**Describe alternatives you've considered**
No alternatives yet, @Paarmita will start working on replicating SVGs of icons we are making use of in the application.

**Additional context**
TODO

**Comment by Paarmita** [comment]
Adding the SVG icons in the footer will resolve this.
The issue for adding those icons- #787

**Comment by Paarmita** [comment]
Removed Font-awesome!
