### ISSUE TITLE
Ignitus Student login/signup component re-use.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#481]
**Is your feature request related to a problem? Please describe.**
Yes, currently Ignitus professor, login/signup has separate HTML, CSS associated with it, but Ignitus student login/signup component can be re-used to do authentication for professor as well.

**Describe the solution you'd like**
Re-use student login/signup component in => professor login/signup.

**Describe alternatives you've considered**
N.A

**Additional context**
Reach me if you struck anywhere. 👨🏻‍💻

**Comment by Marvin9** [comment]
@divyanshu-rawat 
Close this issue.

**Comment by divyanshu-rawat** [comment]
@Marvin9 if you get time can you create components out of login/signup, what I mean is sharedLogin & sharedSignup also share lot of html between them , like except confirm password everything the UI is almost same in both of them, I will split kit out if I get time, if you have you can give it a try.

**Comment by Marvin9** [comment]
I would love to do that. However I am working on GSOC proposals, I will resolve this issue as soon as I got buffer time.
