### ISSUE TITLE
Misalignment on hover.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#517]
**Describe the bug**
As demonstrated in gif once you hover upon team members at http://www.ignitus.org/aboutus, you will notice on hover effect UI distorts or misaligned we need to prevent misalignment of UI on hover.´, earlier it was working fine but not now.
Bug was introduced due to migration to emotion 👩‍🎤some removal of existing logic might have caused the distortion.

Old working version can be seen here - https://deploy-preview-480--peaceful-nightingale-55a1b7.netlify.com/aboutus.

**To Reproduce**
Well demonstrated in gif.

**Expected behaviour**
It should behave as intended like UI distortion should not happen.

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13464678/75193949-85fdde80-5757-11ea-98c1-a120832d3c5b.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Bug was introduced due to migration to emotion 👩‍🎤, some removal of existing logic might have caused the distortion.

**Comment by abhinashgiri** [comment]
Sir, I want to give a try to this issue, if you permit. I'm also a GSSOC 20 participant. I'm a beginner so it might take a little longer. Please assign it to me, Sir.

**Comment by divyanshu-rawat** [comment]
@abhinashgiri go ahead now worries 👍 .

**Comment by divyanshu-rawat** [comment]
@abhinashgiri sorry to say misalignment of hover is again fixed somehow with code refactoring in this pr #524 , now I must say can you pick up another issue? :)

**Comment by abhinashgiri** [comment]
Ok . That's good. Sir should I now unassign myself?

**Comment by divyanshu-rawat** [comment]
@abhinashgiri I will un-assign you thanks :)
