### ISSUE TITLE
Write Unit Tests

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#519]
**Is your feature request related to a problem? Please describe.**
We are planning to write unit test for most of our components.

**Describe the solution you'd like**
One can have a look on existing unit tests, and write new ones.

**Comment by VibavariG** [comment]
Sir, I would like to work on this issue. I'm a beginner so I would like to start with this issue

**Comment by debck** [comment]
@VibavariG  You can start working 👍 . Just let us know for which component you will writing the test case.

**Comment by divyanshu-rawat** [comment]
@VibavariG are you still working on it?

**Comment by Dishebh** [comment]
Is the issue resolved now? If not, can I work on it?

**Comment by Marvin9** [comment]
Unit tests for ```Atoms``` are done. You can take reference from there & write for other parts.

**Comment by Dishebh** [comment]
@divyanshu-rawat @Marvin9 I have added tests for `Organisms`. Pls review, thanks!

**Comment by Dishebh** [comment]
Unit tests are done for `Layouts` as well.
