### ISSUE TITLE
New testimonial carousel design.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#526]
**Is your feature request related to a problem? Please describe.**
We plan to update the current design of our testimonial carousel in Ignitus.

**Describe the solution you'd like**
I have attached the screenshot of design we would like to have.

**Describe alternatives you've considered**
N.A

**Additional context**
<img width="842" alt="Testimonials" src="https://user-images.githubusercontent.com/13464678/75396449-c9418400-58f4-11ea-8b3e-99647da70220.png">

**Comment by priyadarshu** [comment]
Hi would like on this issue. But it is not tagged under gssoc20.

**Comment by gittysachin** [comment]
@priyadarshu surely you can take it up.

**Comment by divyanshu-rawat** [comment]
@priyadarshu Thanks for your interest :)

**Comment by Paarmita** [comment]
@aysp-99 Here

**Comment by aysp-99** [comment]
Okay. I'll start working on it! 👍
