### ISSUE TITLE
Define Types

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#530]
**Is your feature request related to a problem? Please describe.**
A lot of places in the codebase type `any` is used, which doesn't make sense, to would be great if any can be replaced with appropriate types.

**Describe the solution you'd like**
Replace `any` types with the actual types.

**Additional context**
Let me know if the issue is still not clear.

**Comment by vvijayalakshmi21** [comment]
Hi, I would like to work on this,
From what i understand, the term 'any' needs to be replaced with actual types. Is that right?
If that is the case, what should I replace it with?

**Comment by divyanshu-rawat** [comment]
@vvijayalakshmi21 that's good question, any should be replace `any` actual types. Now the question arises by what so its subjective for instance here https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Team/types.ts#L8, we have defined type for git-hub contributors data that we are using here https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Team/Components/Team.tsx#L41 , before that it was `any`, one approach could be to `console.log` property that has a type `any` and then you can see the shape & structure of the data structure by logging it and then accordingly define a type for it, for git-hub what I did is I created a request here `https://api.github.com/repos/Ignitus/Ignitus-rest-api/contributors` observed the data structure for first object in the `array of dictionaries `and created type for it, and in some cases you also need to look TS documentation to proceed ahead.

**Comment by Saumya-Mishra9129** [comment]
Hey!! I want to work on this issue.

**Comment by Saumya-Mishra9129** [comment]
Can I start working with this issue?

**Comment by debck** [comment]
@Saumya-Mishra9129 Go for it.

**Comment by Dishebh** [comment]
I would like to work on the issue.

**Comment by divyanshu-rawat** [comment]
@Dishebh if you are interested you can also pick this up. :)

**Comment by Dishebh** [comment]
@divyanshu-rawat Sure!
