### ISSUE TITLE
Mobile responsive UI for signup/login page

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#541]
**Describe the bug**
Currently, on the mobile view, the title and cards are not aligned according to the expected design.

**Expected behavior**
Make it responsive according to the below-designed screen. 
![Mobile View Signup](https://user-images.githubusercontent.com/26546816/75616510-39007a80-5b52-11ea-8b4e-68911bc9ac6f.png)

**Screenshots**
Current screen
<img width="501" alt="Screenshot 2020-03-01 at 12 15 45 AM" src="https://user-images.githubusercontent.com/26546816/75616513-47e72d00-5b52-11ea-978c-8154a2d2622f.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhishekjain35** [comment]
I would like to work on this issue.

**Comment by Paarmita** [comment]
@abhishekjain35 Sure, give it a shot!

**Comment by abhishekjain35** [comment]
I've submitted pull request, please review it.
