### ISSUE TITLE
Job description page design 🎨 part 2.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#543]
Is your feature request related to a problem? Please describe.
Please refer. #397.

**Comment by SanthoshBalagur** [comment]
@divyanshu-rawat  I will work on this page

**Comment by debck** [comment]
@SanthoshBalagur Yes, you can start working :+1:

**Comment by divyanshu-rawat** [comment]
@SanthoshBalagur thanks for your interest :)

**Comment by divyanshu-rawat** [comment]
@SanthoshBalagur are you still working on this? if yes you only need to design form as a separate component as jobConfirmation(#397 )/jobDescription are similar except the application form, so please create the UI and logic for application form :)

**Comment by SanthoshBalagur** [comment]
@divyanshu-rawat  Yes I'm working on it . Will do.
