### ISSUE TITLE
Careers page design 🎨 part 2.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#547]
Is your feature request related to a problem? Please describe.
please refer #396 for more info.

**Comment by aysp-99** [comment]
Hey! I would like to work on this issue.

**Comment by divyanshu-rawat** [comment]
hey sound good @aysp-99  go ahead 👍

**Comment by aysp-99** [comment]
As kamalkaur is working on careers page part 1 and 2 as well, can you please unassign me the issue, to avoid confusions.

**Comment by divyanshu-rawat** [comment]
@aysp-99 sure :)
