### ISSUE TITLE
Margin Reduction to half.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#549]
**Describe the bug**
Reduce highlighted margin to half, currently it is 10em, reduce it to 5em.

<img width="1372" alt="Screenshot 2020-03-01 at 17 54 09" src="https://user-images.githubusercontent.com/13464678/75629892-65fe6d00-5be6-11ea-9348-ab8d16232e7e.png">

**Comment by msk4862** [comment]
@divyanshu-rawat I want to work on this issue.

**Comment by ashishnagpal2498** [comment]
Hi @divyanshu-rawat , I would like to work on this issue as part of GSSOC'20.

**Comment by divyanshu-rawat** [comment]
@ashishnagpal2498 , sorry but @msk4862 claimed it first let me assign it to him for 2 days, then if won't revert then I will assign it to you :)
