### ISSUE TITLE
Looking for new issues 👋

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#554]
We are opening new issues everyday, please have patience :)

**Comment by yj2303** [comment]
changes in "about us" page

**Comment by Paarmita** [comment]
@yj2303 What suggestions do you have for about us page?

**Comment by yj2303** [comment]
I think we can make it more attractive
> using google fonts
>some small animations 
> lil change in css can make it pretty good
overall website is nicely designed but I found that page not upto the mark so I commented.

**Comment by yj2303** [comment]
would you like to assign this issue to me?

**Comment by Paarmita** [comment]
@yj2303 Thanks for the suggestion, but for now, can you take up some other issues that are opened related to dashboard as we are mainly focusing on that.
