### ISSUE TITLE
Dashboard: Navbar UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#556]
**Describe the solution you'd like**
Implementation of the attached UI of the Dashboard navbar based on code guidelines.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

![rehd](https://user-images.githubusercontent.com/26546816/77682287-fede9900-6f96-11ea-954d-1c9051c0e66a.PNG)

**Comment by gargshruti30** [comment]
@Paarmita 
Hey. I would like to work on this issue.

**Comment by Paarmita** [comment]
Make the elements of the navbar like the dropdown button, search input box, and online dropdown as a shared component that could be used all over the app to make the app consistent. Text is already defined in the code which should be used in this navbar component.

**Comment by gargshruti30** [comment]
@Paarmita  What will be the content of the online dropdown and what's the need for it?

**Comment by Paarmita** [comment]
Content of dropdown will be like this, and it contains various options. You can see Figma designs to better understand all the options.

<img width="785" alt="Screenshot 2020-03-11 at 8 21 14 AM" src="https://user-images.githubusercontent.com/26546816/76392176-4ea34a80-6371-11ea-9f31-47b18bdc15d1.png">

**Comment by gargshruti30** [comment]
@Paarmita Do we have to position the elements according to the CSS given in Figma?

**Comment by Paarmita** [comment]
Not exactly I would say, but you can try to use the same spacing if it works well.

**Comment by AnjaliGarg13** [comment]
@Paarmita @divyanshu-rawat 
I started working on this issue as @gargshruti30 was busy with the other issue. 
What would the UI be after collapsing the navbar button?
Can we use react bootstrap components?

**Comment by Paarmita** [comment]
@AnjaliGarg13 We are migrating bootstrap to styled CSS, so please don't use bootstrap. 
For the collapsing navbar, I could provide you the UI by today.

**Comment by Paarmita** [comment]
@AnjaliGarg13 We are migrating bootstrap to styled CSS, so please don't use bootstrap. 
For the collapsing navbar, don't think about it now, just make it responsive till iPad. 

I have an idea like this for the navigation in mobile - Combination of side and bottom menu. 
You can try working on it, but it's not important at the moment. 

![Bottom menu](https://user-images.githubusercontent.com/26546816/77060697-4c786600-69d9-11ea-941c-6a0a5f1aadc1.png)

![Side menu](https://user-images.githubusercontent.com/26546816/77060699-4d10fc80-69d9-11ea-86d8-3e3751f8848d.png)
