### ISSUE TITLE
Dashboard: Side footer

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#557]
**Describe the solution you'd like**
Implementation of the attached UI of the Dashboard footer section based on code guidelines.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

![footer](https://user-images.githubusercontent.com/26546816/75677565-0eb2d800-5c8c-11ea-970d-6f373b03d65c.PNG)

Make this footer as a shared component that could be used all over the app to make the app consistent. Text is already defined in the code which should be used in this component.

**Comment by hudlerr** [comment]
Hi! Could I have a go at this issue?

**Comment by Paarmita** [comment]
@hudlerr Sure!
