### ISSUE TITLE
Dashboard: Side Profile section

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#558]
**Describe the solution you'd like**
Implementation of the attached UI of the Dashboard side profile section based on code guidelines.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

![profile card](https://user-images.githubusercontent.com/26546816/75678568-399e2b80-5c8e-11ea-91cb-42875e107399.PNG)

**Comment by priyadarshu** [comment]
Hi would like to work on this .

**Comment by Paarmita** [comment]
Make the elements of the profile section like the View Profile button as a shared component that could be used all over the app to make the app consistent. Text is already defined in the code which should be used in this component.

**Comment by divyanshu-rawat** [comment]
@priyadarshu you can place shared components here - https://github.com/Ignitus/Ignitus-client/tree/master/src/shared :)

**Comment by priyadarshu** [comment]
I had edited src/ignitus-Dashboard-Profile-Section/Components/dashBoardProfileSection.js file based on the Figma design. But couldn't check if its actually working, may i directly send a push request

**Comment by gittysachin** [comment]
@priyadarshu please link your pull request to this issue.

**Comment by aysp-99** [comment]
Is Priyadarshini still working on it?

**Comment by Paarmita** [comment]
No Asfiya, you can go ahead & work on it. :)
