### ISSUE TITLE
Dashboard: Side Navigation

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#559]
**Describe the solution you'd like**
Implementation of the attached UI of the Dashboard side Navigation section based on code guidelines.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

![side navigation](https://user-images.githubusercontent.com/26546816/75678628-59355400-5c8e-11ea-9328-69e694bcb942.PNG)

Hover state- 
![Group 13](https://user-images.githubusercontent.com/26546816/75679343-baa9f280-5c8f-11ea-96f9-97cbe1ebb1c3.png)

Make this Side navigation as a shared component that could be used all over the app to make the app consistent. Text is already defined in the code which should be used in this component.

**Comment by gargshruti30** [comment]
@Paarmita 
Hey. I would like to work on this issue.

**Comment by Paarmita** [comment]
@gargshruti30 It would be great if you can take up to 2 issues at a time and please make a PR for them and then take up new issues.

**Comment by tanisha03** [comment]
@Paarmita I would like to give it a try

**Comment by divyanshu-rawat** [comment]
@tanisha03 go ahead 👍

**Comment by divyanshu-rawat** [comment]
Please go through #605 before staring this issue, ignore if you have already created a branch out of master.
