### ISSUE TITLE
Add BOT

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#56]
Add bot to the Ignitus repository for instance gitMate, Netlify etc.
Feel free to add any bot that you think is help to the community/ IgnitusClient side repository.

**Comment by debck** [comment]
I think adding Netlify will be good one

**Comment by divyanshu-rawat** [comment]
@debck can you add one?

**Comment by debck** [comment]
No, I was just keeping my view that if someone wants to add anything , then Netlify would be good choice.:smile:

**Comment by debck** [comment]
Okay @divyanshu-rawat  I will add

**Comment by debck** [comment]
But, How should I login into Netlify, use my own GitHub account, or from the org.

**Comment by divyanshu-rawat** [comment]
@debck will DM you ignitus-bot github account credentials.

**Comment by divyanshu-rawat** [comment]
@debck I have already added that 👍
