### ISSUE TITLE
Dashboard: Dropdown UI for navbar

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#560]
**Describe the solution you'd like**
Implementation of the attached UI of the dropdown in the Navigation bar based on code guidelines.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

Part of the issue: #556 

![navbar dropdowns](https://user-images.githubusercontent.com/26546816/75679496-09578c80-5c90-11ea-93ff-ed2fb1a0ae24.PNG)

Hover for Search dropdown-
![Group 15](https://user-images.githubusercontent.com/26546816/75680457-f1810800-5c91-11ea-894f-e5cb685e8397.png)

**Comment by AnjaliGarg13** [comment]
@Paarmita 
Hey, I would like to work on this issue.

**Comment by Paarmita** [comment]
@AnjaliGarg13 Please keep in mind this could only be done after the #556 is done as it requires to make a UI for the dropdown in the Navbar.

**Comment by AnjaliGarg13** [comment]
I will coordinate with my teammate (RGSOC 2020) @gargshruti30 regarding #556 before getting started.

**Comment by divyanshu-rawat** [comment]
Please go through #605 before staring this issue, ignore if you have already created a branch out of master.

**Comment by Paarmita** [comment]
@Meghana-12 Are you working on this?

**Comment by Meghana-12** [comment]
Yes, @Paarmita.

**Comment by Paarmita** [comment]
@Meghana-12 Would you like to work on other dropdown UI also?

**Comment by Meghana-12** [comment]
sure, I'll work on it.
