### ISSUE TITLE
Write reusable code for login and sign up page

### ISSUE THREAD

**Issue by steric85** [Ignitus/Ignitus-client#565]
**Is your feature request related to a problem? Please describe.**
Code for `CommonSignUpUI` and `CommonLoginUI` is redundant. 

**Describe the solution you'd like**
We can create a single prop-driven component that can achieve both login and sign up functionalities.

**Comment by divyanshu-rawat** [comment]
hey @steric85 thanks for opening the issue I was also thinking to open one :) , and one more thing could you also use TypeScript when you create a reusable component.

**Comment by steric85** [comment]
Yes, sure! 
I've made the changes in TS and pushed to #548

**Comment by divyanshu-rawat** [comment]
Thanks :)

**Comment by ShauryaBhandari** [comment]
Hi! Has this issue been resolved? Or is some help still needed?
Thanks.

**Comment by Paarmita** [comment]
@steric85 Are you still working on this issue?

**Comment by divyanshu-rawat** [comment]
Please go through #605 before staring this issue, ignore if you have already created a branch out of master.

**Comment by divyanshu-rawat** [comment]
#548 Resolves it.
