### ISSUE TITLE
404 error page UI: Add lottie animation

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#567]
Update the 404 error page with the new design and add the provided Lottie animation. 
You can read some blogs for integrating the Lottie with react apps.

New Design

![404 error page](https://user-images.githubusercontent.com/26546816/75749526-4bc9a980-5d22-11ea-9b42-428169155d1a.png)

Download JSON Lottie file- 

https://assets9.lottiefiles.com/packages/lf20_Ge1Qcq.json

**Comment by APOORVA456** [comment]
I want to work on this issue.

**Comment by Paarmita** [comment]
@APOORVA456 Sure, go for it!

**Comment by beingKHUSH** [comment]
Is it possible that more than one participant can work on the same issue. Since, I too want to work on this issue.

**Comment by debck** [comment]
Sorry @beingKHUSH but only one person should work on an issue so that there are no duplicate PRs.
If we see no progress on this issue in 2-3 days then we will assign it to you 😃
You can assign yourself other issues in the meantime.
