### ISSUE TITLE
Make Homepage responsive

### ISSUE THREAD

**Issue by debck** [Ignitus/Ignitus-client#569]
**Describe the solution you'd like**

The homepage isn't responsive for most devices. So task is to make the homepage/ landing page responsive keeping the design 

Page: http://www.ignitus.org/

**Comment by John123Allison** [comment]
Hi, can I take this?

**Comment by John123Allison** [comment]
I'm not sure exactly what you're looking for - I tested the website on a few devices and it seemed fine as is. Could you please elaborate?

Thanks (:

**Comment by divyanshu-rawat** [comment]
@John123Allison sure I respect your opinion, we plan to close this issue as website already seems quite responsive maybe because of some recent contributions after opening this issue.
Feel free to pick another issue to work on. 👍
