### ISSUE TITLE
TypeScript Support with Hound

### ISSUE THREAD

**Issue by debck** [Ignitus/Ignitus-client#570]
**Is your feature request related to a problem? Please describe.**

  As we are migrating to TypeScript recently, we will require to update our hound config to support TS.
Currently, we have the configuration for eslint and javascript. 

**Describe the solution you'd like**

You have to add the TS support in the ` .hound.yml` file here: https://github.com/Ignitus/Ignitus-client/blob/master/.hound.yml

**For Reference**

   http://help.houndci.com/en/articles/2138544-tslint

Thanks 😃

**Comment by abhu-A-J** [comment]
@debck can I work with this? It looks straightforward. Thanks!

**Comment by gittysachin** [comment]
Go ahead @abhu-A-J 👍
