### ISSUE TITLE
Hide Testimonial on small screen (Mobile devices)

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#572]
**Is your feature request related to a problem? Please describe.**
It would be great if we won't show testimonial component on small screen device as it doesn't look good on small screen, so better hide it.

**Approach:**
Writing a media-query will do the job, lets hide for `screen width < 576px`

**Comment by abhu-A-J** [comment]
@divyanshu-rawat Can I try this. I am GSSoC participant

**Comment by gittysachin** [comment]
> @divyanshu-rawat Can I try this. I am GSSoC participant

Sure, give it a shot 👍

**Comment by debck** [comment]
Yes, sure @abhu-A-J . Go for it
