### ISSUE TITLE
Implement register/login for professor   🎓.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#573]
**Is your feature request related to a problem? Please describe.**
Implement `register/login` for professor.  🎓

**Describe the solution you'd like**
Currently `login/register` for `student` is already implemented, someone just have to replicate the same for `professor`.

**Describe alternatives you've considered**
N.A

**Additional context**
Here are the backend endpoints for the same.
https://github.com/Ignitus/Ignitus-rest-api/blob/master/api/Controllers/user.js

**Comment by NVS16** [comment]
Can I work on this?

**Comment by gittysachin** [comment]
@NVS16, sure. Give it a try 👍

**Comment by divyanshu-rawat** [comment]
sure @NVS16  ⚡️

**Comment by divyanshu-rawat** [comment]
Please go through #605 before staring this issue, ignore if you have already created a branch out of master.

**Comment by Marvin9** [comment]
@divyanshu-rawat I would take this up. Please update endpoints link.

**Comment by divyanshu-rawat** [comment]
@Marvin9 no please go ahead 👍
