### ISSUE TITLE
Improve code quality 🔨 🧹readability. 

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#574]
**Is your feature request related to a problem? Please describe.**
1 - Fix ESLINT warnings, instead of disabling them, in many files you will comments on the top like this. 🧹 🔨

```
/* eslint-disable react/prop-types */
/* eslint-disable class-methods-use-this */
/* eslint-disable jsx-a11y/mouse-events-have-key-events */
```

These comments are basically suppressing the ESLINT warnings, and if you remove those comments then ESLINT will show you what needs to be fixed in that file to align with ESLINT guidelines, we have added comments in the past to suppress those warnings, but now we plan to fix them.

2 - Replace old JS syntax in the code base with new ES6 Syntax. 🔨
3 - At lot of places in the code base `margin`, `padding`  are defined in `px`, `rem` ,`em` I believe we should have consistency what I mean is replace all the occurrences of `px`, 'em'  in margin, padding properties by `rem`. 🎨

**IMP:** Please don't change `media-queries` to `rem`, they should be in `px`, as we decide our breakpoints according to them :).

4 - At lot of places in the the codebase, margin & padding are written as `padding-left`, `padding-right`, `margin-top`, `margin-bottom`. if there are more than one occurrence of padding and margin in the same css property for instance 🎨.

```
.abc { 
  margin-left: 2px;
  margin-right: 2px;
}
```

then replace them with shorthand property like this.

```
.abc { 
  margin: 0 2px;
}

```
5 - Suggestions are welcome to improve the way code is written.

**Additional context**
You need not to solve this issue for entire codebase, even solving it in **1** file and creating a PR is fine for us.

**Comment by vvijayalakshmi21** [comment]
Hi, I would like to do this.

**Comment by gittysachin** [comment]
> Hi, I would like to do this.

Sure, go ahead 😊

**Comment by divyanshu-rawat** [comment]
Thanks @vvijayalakshmi21 for your interest :) , feel free to give suggestions on code quality, readability to us as well if you have any.

**Comment by abhu-A-J** [comment]
Hello Mentors, I'll like to work on this particularly on styling aspect. The components I have picked up:
1. Ignitus-Footer (px to rem conversion)
2. Ignitus-Introduction (px to rem, and add standard property of background-clip for compatibility which is missing, so shows error (although not a breaking issue))
3. Ignitus-Getting Started (px to rem)

Also i would like to know if any reset has been done of body font-size for accurate units conversion.
So is 1rem:16px or reset is done to make 1rem:10px. ??Thanks

**Comment by divyanshu-rawat** [comment]
@abhu-A-J thanks a lot for your interest :) No reset is done so `1rem` should be `16px`. let me know if you have any other questions 👍

**Comment by divyanshu-rawat** [comment]
@vvijayalakshmi21 please don't pick those components that @abhu-A-J has already picked :)
