### ISSUE TITLE
Error message UI fix.

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#578]
**Describe the bug**
Text is not aligned correctly when Contributors are not loaded properly and looks something like this. 

<img width="1440" alt="Screenshot 2020-03-04 at 9 34 30 PM" src="https://user-images.githubusercontent.com/26546816/75920755-45414c00-5e60-11ea-9b9a-9158d51d3799.png">

**Expected behavior**
It should be aligned properly with proper font size. Try it in your way, or let me know if you need any help with the design.

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue.

**Comment by shreyakapoor08** [comment]
Hey, I want to work on this issue

**Comment by divyanshu-rawat** [comment]
@ashishnagpal2498 you are already assigned to https://github.com/Ignitus/Ignitus-client/issues/585. So, I am assigning this to @shreyakapoor08.

**Comment by Paarmita** [comment]
@shreyakapoor08 Sorry, I couldn't provide a proper UI for this, but here it is, can you please add this text with defined spacing.

<img width="781" alt="Screenshot 2020-03-10 at 12 07 58 AM" src="https://user-images.githubusercontent.com/26546816/76264894-5ecd0400-6263-11ea-82ce-b1c3e823159a.png">

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 Sorry, I couldn't provide a proper UI for this, but here it is, can you please add this text with defined spacing.
> 
> <img alt="Screenshot 2020-03-10 at 12 07 58 AM" width="781" src="https://user-images.githubusercontent.com/26546816/76264894-5ecd0400-6263-11ea-82ce-b1c3e823159a.png">

Hey @Paarmita I have made the appropriate changes. Please check. I am attaching the snippet below

![Capture](https://user-images.githubusercontent.com/31164665/76280141-e98b1e80-62b6-11ea-9281-096485809bd3.JPG)

**Comment by Paarmita** [comment]
@shreyakapoor08 Looks good! Thanks for the changes, it would be great if you can also add a bit more margin on top and bottom of this section similar to what other sections have.

**Comment by divyanshu-rawat** [comment]
Please go through #605 before staring this issue, ignore if you have already created a branch out of master.

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 Looks good! Thanks for the changes, it would be great if you can also add a bit more margin on top and bottom of this section similar to what other sections have.

I have done the corrections. Kindly check
