### ISSUE TITLE
Removal of Bootstrap 4 in Nav-bar. 🎨

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#580]
**Is your feature request related to a problem? Please describe.**
Remove `Bootstrap 4` classes used in `navigation-bar` with `custom css`, one way is to copy properties associated with BS4 classes and add those properties to your `custom classes`, or design `navigation-bar` from scratch using your own css.

**Describe the solution you'd like**
Remove `navigation-bar` BS4 => Pure css.

**Describe alternatives you've considered**
Issue can be considered part of #403 

**Additional context**
Let me know if issue is not clear. ⚡️

**Comment by abhishekjain35** [comment]
I would like to work on this issue, kindly assign it to me.

**Comment by divyanshu-rawat** [comment]
sure go ahead 👍 .

**Comment by ShauryaBhandari** [comment]
Hi! I would like to work on this issue if it has still not been resolved. 
Thanks!

**Comment by gittysachin** [comment]
@abhishekjain35 are you still working on this issue?

**Comment by shreyakapoor08** [comment]
I want to work on this issue. @gittysachin @divyanshu-rawat

**Comment by gittysachin** [comment]
@ShauryaBhandari you can start working on this issue 👍

**Comment by divyanshu-rawat** [comment]
@ShauryaBhandari Please go through #605 before staring this issue.

**Comment by ShauryaBhandari** [comment]
Hi! I am so sorry for replying late, I will be starting tonight. Thanks for assigning it to me and apologies.

**Comment by abhu-A-J** [comment]
@divyanshu-rawat  Can I do this task?? No PR seems to be made this now?

**Comment by divyanshu-rawat** [comment]
@abhu-A-J please go ahead, and let me know if you need any help or struck anywhere :)
