### ISSUE TITLE
Optimise app as per light-house report.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#584]
Please find attached google light-house repot for http://www.ignitus.org.

Screenshot won't show you everything.

![screencapture-googlechrome-github-io-lighthouse-viewer-2020-03-05-16_58_44](https://user-images.githubusercontent.com/13464678/75999633-cfda8780-5f02-11ea-9f00-3b8f1b69e0f7.png)

So, I would suggest to navigate [here](https://googlechrome.github.io/lighthouse/viewer/?psiurl=http%3A%2F%2Fwww.ignitus.org%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext) for detailed report.

**Comment by adityasanil** [comment]
Can I take up this?

**Comment by Paarmita** [comment]
@adityasanil Sure go for it.

**Comment by divyanshu-rawat** [comment]
Please go through #605 before staring this issue.

**Comment by adityasanil** [comment]
Sure.

**Comment by divyanshu-rawat** [comment]
If you plan to work on lazy-loading of images, then please don't use any additional `NPM` package to do so, it would be great if you can find some way to do the same without relying on NPM Package.
