### ISSUE TITLE
Restrict Contributors count. ★

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#585]
**Is your feature request related to a problem? Please describe.**
Currently if you navigate to `http://www.ignitus.org/aboutus` and scroll down you will see a list of contributors that keeps on growing with passage of time.
we would like to restrict it to lets say something like `14+ contributors` instead of showing all of them.

**Describe the solution you'd like**
Please find attached screenshot that shows similar picture, I contributed to storybook once to restrict the contributors-

**Current Scenario**
This is how it looks at the moment.

![Screenshot 2020-03-05 at 21 29 29](https://user-images.githubusercontent.com/13464678/76024565-9ec27d00-5f2b-11ea-8ca1-7947e3b6dadf.png)

**Expectation**
![Screenshot 2020-03-05 at 21 14 09](https://user-images.githubusercontent.com/13464678/76021866-5359a000-5f26-11ea-8d2a-4a2d5f184dbc.png)

**IMP:** Please don't change the UI, we are fine with current our current UI we just plan to implement the functionality to restrict the umber fo contributors.

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue - GSSOC 20.

**Comment by gittysachin** [comment]
Sure @ashishnagpal2498, go for it ⚡
