### ISSUE TITLE
Site under build page UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#594]
On the develop branch, currently, no dashboard UI has been built, so I wanted a site under build banner message for the users who register.

Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

![Maintenance page](https://user-images.githubusercontent.com/26546816/76172965-324db500-619b-11ea-9350-ed81a3a8599a.png)

**Comment by BhuwanChandra** [comment]
@Paarmita I would like to work on this issue. please assign this to me

**Comment by gittysachin** [comment]
@BhuwanChandra Sure, go ahead. Please remember to create pull request from `develop` branch.

**Comment by BhuwanChandra** [comment]
@gittysachin in which folder do I need to create this site under build banner component?

**Comment by gittysachin** [comment]
@BhuwanChandra make this component inside `Ignitus-client/src/ignitus-Dashboard/
` folder. @Paarmita do we want to make this for `master` or `develop`? Because we recently updated our guidelines for contribution.

**Comment by divyanshu-rawat** [comment]
@gittysachin everything should be merged to `master` in the end, so every new branch will be created out fo `develop`, and eventually everything from `develop` will be merged to master once we are ready for release, So, it should be for develop, we will never create a PR to `master` directly :)

**Comment by gittysachin** [comment]
Thanks @divyanshu-rawat :)
