### ISSUE TITLE
After Signing Up, it produces the Sign Up page only.

### ISSUE THREAD

**Issue by kamal-kaur04** [Ignitus/Ignitus-client#601]
**Is your feature request related to a problem? Please describe.**
When I press Sign up (as student/Professor) button after filling information to sign up, it opens the sign up page again. 

**Describe the solution you'd like**
I feel that after sign up, it should redirect the user to Sign In page.

![ignitus_feature_1](https://user-images.githubusercontent.com/38219887/76305940-0ee64f80-62ec-11ea-9b35-44d6e7b5357c.gif)

**Comment by gittysachin** [comment]
Thanks for opening this issue @kamal-kaur04. But it should also flash the message `Success! Please Login!` on the login page.

**Comment by kamal-kaur04** [comment]
@gittysachin then we can show that in alert box that can popup after submitting the sign-up form.

**Comment by gittysachin** [comment]
No @kamal-kaur04, make that same as we did on the signup page, as it showed `Success! Please Login!` above the form. But it should redirect to login page and show that same flash there. No alert box or popup.

**Comment by kamal-kaur04** [comment]
Okay @gittysachin Can I take this up?

**Comment by gittysachin** [comment]
Sure @kamal-kaur04, go for it ⚡️

**Comment by Paarmita** [comment]
Resolved
