### ISSUE TITLE
Dashboard: Profile Main section UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#607]
**Describe the solution you'd like**
Implementation of the attached UI of the Profile Section in the Profile screen based on code guidelines.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

![profile information](https://user-images.githubusercontent.com/26546816/76422570-b4a9c500-63a5-11ea-8c31-5864e56a5710.png)

Dropdown UI for More option

![Capture](https://user-images.githubusercontent.com/26546816/76422885-3994de80-63a6-11ea-9941-96ad9e1c2b49.PNG)

Please make the button, cards, etc as a shared component that could be used all over the app to make the app consistent. Text is already defined in the code which should be used in this component.

**Comment by ashishnagpal2498** [comment]
Hey @Paarmita  can I work on this issue ?

**Comment by Paarmita** [comment]
@ashishnagpal2498 Sure, go for it!

**Comment by ashishnagpal2498** [comment]
Hi @Paarmita  , I am facing a bit issue in putting "chat" and "resume - page" icon as font-awesome are paid and svg is not working. Can you please help regarding this ?

**Comment by Paarmita** [comment]
@ashishnagpal2498 In which format do you need them?

**Comment by ashishnagpal2498** [comment]
@Paarmita the one supported by font-awesome as Icon.
