### ISSUE TITLE
Dashboard: Settings Page Side Navigation

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#608]
**Describe the solution you'd like**
Implementation of the attached UI of the Side navigation in the Settings screen based on code guidelines.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

![Capture](https://user-images.githubusercontent.com/26546816/76423190-ae681880-63a6-11ea-8309-bb191ab129cb.PNG)

Please make the button, cards, etc as a shared component that could be used all over the app to make the app consistent. Text is already defined in the code which should be used in this component.

Refer to the Home Side Menu with icons for design in this issue, try to use the same component but without the icons #559

**Comment by ashishnagpal2498** [comment]
Can I work on this issue ?

**Comment by Paarmita** [comment]
@ashishnagpal2498 Please provide a PR for #607, then take up new issues.

**Comment by shreyakapoor08** [comment]
can i take up this issue?
