### ISSUE TITLE
Dashboard: Opportunities Filters

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#609]
**Describe the solution you'd like**
Implementation of the attached Opportunity based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Templates](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/uikit` route. 
But you would need to divide this component into different atoms and molecules:
- **Tags** ,**dropdown**, **Dropdown buttons** and **reset filter button** will come under `Atoms`
- **Search** input will come under `Molecules`
- Card CSS should be the same as mentioned in Atoms. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

![Capture](https://user-images.githubusercontent.com/26546816/76427638-da869800-63ac-11ea-9b9f-4dca32d7897b.PNG)

For each dropdown refer to the images below.

![Internship Date-dropdown](https://user-images.githubusercontent.com/26546816/76427713-f12cef00-63ac-11ea-81dc-a0f9051d4d3c.png)

![Internship Job-dropdown](https://user-images.githubusercontent.com/26546816/76427716-f1c58580-63ac-11ea-9631-e430e2857180.png)

![Internship Location-dropdown](https://user-images.githubusercontent.com/26546816/76427718-f1c58580-63ac-11ea-8e07-e10fdd907fe2.png)

**Comment by BhuwanChandra** [comment]
@Paarmita I would like to work on this issue. please assign this to me.

**Comment by gittysachin** [comment]
Go for it @BhuwanChandra ⚡️

**Comment by BhuwanChandra** [comment]
@gittysachin in which folder do I need to create opportunities filters?

**Comment by Paarmita** [comment]
@BhuwanChandra I have updated the issue description with all the details.

**Comment by BhuwanChandra** [comment]
@gittysachin but @Paarmita said in the issue description that it should be under ignitus-UserInterfaceKit folder. in which should I create that?

**Comment by gittysachin** [comment]
Oh, My bad! @BhuwanChandra I didn't see the updated version of the description. 

Yes Exactly, you need to create the folder under [/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates). Create a new folder here `ignitus-FilterComponents/Opportunity`.
