### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#610]
It would be great for us if you could spare some time ⏰ to provide the UX feedback 📋 on the designs. 
It will also help you to better understand what you will be building and working on. 

View Screens in [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) and comment 💬 on the screens to provide feedback 📋. You can also comment below in this issue. 👊

Do let me know if you want to work on the UI\UX of the Web or Mobile app, we can have a chat and talk further about it. 👩‍💻

Really excited to your feedbacks. 😃

**Comment by chhavikirtani2000** [comment]
Hi!
I am a member of cdTech team and we are planning on participating in RGSoC'20. We would like to start making small contributions to this project. Please guide us further
Thanks for your time.

**Comment by Paarmita** [comment]
@chhavikirtani2000 Welcome! You can join the slack (https://igniteus.slack.com/join/shared_invite/enQtNDE2MzM1MTg1NDczLWM1NzAzYzhlYmU3ODRkMjIyZjE3YjFlMzQ2ODljYzhhMjdiNzZjZDc3OTIyNGEwNjE4NDYwMGM0NjExZDE0ZjE ) and can contact @divyanshu-rawat for further contribution.

**Comment by divyanshbhowmick** [comment]
I would like to fix this up!

**Comment by Prahitha** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/44160152/77830833-5a548680-7151-11ea-8ddf-dbbae4514f30.png)

I think the cards would look better (on hover), if they have some margin around them.
