### ISSUE TITLE
Improvement in CONTRIBUTION.md

### ISSUE THREAD

**Issue by kamal-kaur04** [Ignitus/Ignitus-client#616]
**Describe the bug**
CONTRIBUTION.md says,

1. Fork the repository.
`https://github.com/your_username/Ignitus-client.git`

2. Clone the repository.
`git clone https://github.com/Ignitus/Ignitus-client.git`

**To Reproduce**
`Ignitus-client/.github/CONTRIBUTION/CONTRIBUTION.md`

**Expected behavior**
I guess this should be like.
1. Fork the repository.
`https://github.com/Ignitus/Ignitus-client.git`

2. Clone the repository.
`git clone https://github.com/your_username/Ignitus-client.git`

**Screenshots**
![Screenshot from 2020-03-12 21-13-47](https://user-images.githubusercontent.com/38219887/76540004-8ca28a80-64a7-11ea-8cf1-6169b730d31b.png)

**Comment by debck** [comment]
@kamal-kaur04 If you want, you can solve the issue

**Comment by kamal-kaur04** [comment]
Yes, I would like to solve. Thanks.
