### ISSUE TITLE
Navbar after signup does not show that the user is logged in

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#618]
**Describe the bug**
After Signup or login, if you go back to the homepage, the navigation doesn't show that you are logged in or do not have any link to view the dashboard. 

**Expected behaviour**
The Navbar should change if the user is signed in already, just for now till the dashboard is not fully developed.

**Screenshots**
After signup Navbar should look like this 

<img width="1440" alt="Screenshot 2020-03-12 at 8 59 25 PM" src="https://user-images.githubusercontent.com/26546816/76561986-b60de700-64a4-11ea-9ad3-d7c5264172ae.png">

**Comment by Saumya-Mishra9129** [comment]
I would like to work on this issue!!

**Comment by gittysachin** [comment]
Sure @Saumya-Mishra9129. Go ahead 👍

**Comment by Satyam3976** [comment]
@Paarmita Please assign me this issue, I want to work on this.

**Comment by Satyam3976** [comment]
Please assign me this Issue. I wanted to work on this.

**Comment by BhuwanChandra** [comment]
@Paarmita I would like to work on this issue. please assign this to me.

**Comment by divyanshu-rawat** [comment]
@Satyam3976 go ahead, and let me know if you still want to work on it else we will assign it to @BhuwanChandra  :)
