### ISSUE TITLE
Dashboard: Internship List view

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#619]
**Describe the solution you'd like**
Implementation of the attached UI of a list view of opportunities based on code guidelines.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

<img width="610" alt="Screenshot 2020-03-12 at 3 15 38 PM" src="https://user-images.githubusercontent.com/26546816/76562696-35e88100-64a6-11ea-86fc-d215aa75269f.png">

Please make this as a shared component that could be used all over the app to make the app consistent. Text is already defined in the code which should be used in this component.

**Comment by ashishnagpal2498** [comment]
Hi @Paarmita , I have raised the PR for the other issue , I'll be doing the changes side by side. Can I work on this issue ?

**Comment by gittysachin** [comment]
Sure @ashishnagpal2498, go for it ⚡. But please make sure to work on the previous PR as well.
