### ISSUE TITLE
Make the white background navbar as constant

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#629]
**Describe the bug**
Currently, the navbar is not visible until we scroll and then the navbar background changes to white which is visible on grey backgrounds.

**Expected behaviour**
The white background navbar should remain constant and not change on the scroll.

**Screenshots**
![ezgif-6-dc87eef1079f](https://user-images.githubusercontent.com/26546816/76674026-7120a800-65ab-11ea-94d4-c7db7d5f6edc.gif)

**Comment by abhu-A-J** [comment]
@Paarmita Am  I allowed to  work on this??

**Comment by Paarmita** [comment]
@abhu-A-J  Sure!

**Comment by abhu-A-J** [comment]
@Paarmita  Soory  I didn't really check this message before . You can close the [PR](https://github.com/Ignitus/Ignitus-client/pull/632) .

**Comment by Saumya-Mishra9129** [comment]
I would like to work on this issue

**Comment by Paarmita** [comment]
@Saumya-Mishra9129 Sure go-ahead

**Comment by Paarmita** [comment]
@Saumya-Mishra9129 Do wait for some time, as we need to discuss whether to make it constant or not. See discussion here #540

**Comment by Paarmita** [comment]
@Saumya-Mishra9129 make the navbar constant for these pages, `UIkit`, `Notfound`, `Site under construction`, `Careers`,  `Authentication- login signup`  and for `Home` and `About`. it remains the same.

**Comment by divyanshbhowmick** [comment]
I would like to fix up this issue. Please assign it to me!

**Comment by Paarmita** [comment]
@Saumya-Mishra9129 Are you still working on this issue?
@divyanshbhowmick Let's wait for Saumya#s reply, otherwise you can take this up.

**Comment by divyanshbhowmick** [comment]
Okay I will wait!

**Comment by FrozenGirl-spd** [comment]
@Paarmita  Can i work on the issue please?!

**Comment by Saumya-Mishra9129** [comment]
@Paarmita I have worked on this issue and send you a pull request

**Comment by Adyasha8105** [comment]
@divyanshu-rawat @Paarmita  Can I work on this issue?

**Comment by Paarmita** [comment]
@Adyasha8105 Sure

**Comment by Paarmita** [comment]
@Adyasha8105 Sorry, it's a priority task so some maintainer of the project will be working on it. 
@Marvin9 Can you please take this up?

**Comment by Marvin9** [comment]
Sure
