### ISSUE TITLE
Implement Login/Logout 

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#64]
**Is your feature request related to a problem? Please describe.**
User Authentication/Authorization

**Describe the solution you'd like**
Implement Login/Logout routes in client side.

**Describe alternatives you've considered**
JWT Authentication on the rest-api.

**Additional context**
Rest API - https://github.com/Ignitus/Ignitus-rest-api
We have already writen the restful api for user registration and use authentication but currently on the client side we only have static user registration(SIGN UP) and authentication forms(SIGN IN), it would be great if we can integrate backend and frontend.

Kindly let me know if you have any other Questions 👍

**Comment by agoiabel** [comment]
I would like to take up this

**Comment by divyanshu-rawat** [comment]
Yes @agoiabel go ahead 👍

**Comment by agoiabel** [comment]
Finding it hard to install this locally.

**Comment by divyanshu-rawat** [comment]
@agoiabel for setting up locally kindly follow - https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/master/CONTRIBUTION.md
