### ISSUE TITLE
Dashboard: Toggle button UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#644]
**Describe the solution you'd like**
Implementation of the attached Toggle button based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Molecules](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/uikit` route. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

![feed toggle](https://user-images.githubusercontent.com/26546816/77062240-c6a9ea00-69db-11ea-81db-2242f6ca84bd.png)

![grid icons](https://user-images.githubusercontent.com/26546816/77085372-8a3cb500-6a00-11ea-8b5c-515f5bba54d4.png)

**Comment by akansha006** [comment]
I would like to take up this issue. Please assign this to me.

**Comment by divyanshu-rawat** [comment]
go ahead 👍

**Comment by divyanshu-rawat** [comment]
@akansha006 are you still working on this ?

**Comment by Adyasha8105** [comment]
@Paarmita @divyanshu-rawat Can I do this?

**Comment by Paarmita** [comment]
@Adyasha8105 Yes, you can take up, as @akansha006 haven't responded.

**Comment by Adyasha8105** [comment]
@Paarmita Can you explain this issue as I am unable to understand it?

**Comment by divyanshu-rawat** [comment]
cc @Paarmita

**Comment by Paarmita** [comment]
@Adyasha8105 I guess everything is mentioned in the description like which files to add the component, just follow the code structure and implement the component.

**Comment by Dishebh** [comment]
Can I take this issue, if no one else is working on it?

**Comment by Dishebh** [comment]
@Paarmita do I have to make a new `interfaceToggleButtons` under `Molecules` at `/interface/toggleButtons` route?

**Comment by Paarmita** [comment]
@Dishebh Yes

**Comment by Dishebh** [comment]
![image](https://user-images.githubusercontent.com/43489708/80859486-150b0380-8c7f-11ea-8bb8-c4d1c0fdc563.png)

Are these icons available in the repo?

**Comment by Paarmita** [comment]
@Dishebh I guess no, you need to add them from material rounded icons.
