### ISSUE TITLE
Dashboard: Input fields UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#649]
**Describe the solution you'd like**
Implementation of all the Input fields based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Atoms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.
Navbar Search
<img width="222" alt="Screenshot 2020-03-20 at 1 27 39 AM" src="https://user-images.githubusercontent.com/26546816/77146791-2e1f7280-6a8c-11ea-8f3f-91bbb03ac6a4.png">

Navbar Search Input
<img width="210" alt="Screenshot 2020-03-20 at 1 27 53 AM" src="https://user-images.githubusercontent.com/26546816/77146792-2f509f80-6a8c-11ea-8dec-fddb30e4eab7.png">

Search Input
<img width="339" alt="Screenshot 2020-03-20 at 1 28 22 AM" src="https://user-images.githubusercontent.com/26546816/77146795-2f509f80-6a8c-11ea-9c94-1a45cd07f725.png">

Input with Icon
<img width="490" alt="Screenshot 2020-03-20 at 1 28 46 AM" src="https://user-images.githubusercontent.com/26546816/77146796-2fe93600-6a8c-11ea-8fdb-80615842c782.png">

Multimedia Text input
<img width="368" alt="Screenshot 2020-03-20 at 1 29 01 AM" src="https://user-images.githubusercontent.com/26546816/77146895-6fb01d80-6a8c-11ea-8d71-c8e351529472.png">

Delete Account Text Area
<img width="441" alt="Screenshot 2020-03-20 at 9 22 28 AM" src="https://user-images.githubusercontent.com/26546816/77146908-72ab0e00-6a8c-11ea-920b-4b35069c2193.png">

**Forms**
Profile Form- All text inputs
<img width="289" alt="Screenshot 2020-03-20 at 9 21 53 AM" src="https://user-images.githubusercontent.com/26546816/77146899-7048b400-6a8c-11ea-8259-45945ac88408.png">

Settings form
<img width="429" alt="Screenshot 2020-03-20 at 9 22 21 AM" src="https://user-images.githubusercontent.com/26546816/77146904-7179e100-6a8c-11ea-9274-e6d2ae7ed0a0.png">

Email input
<img width="383" alt="Screenshot 2020-03-20 at 9 22 34 AM" src="https://user-images.githubusercontent.com/26546816/77146909-72ab0e00-6a8c-11ea-8a60-3bd6610cc83a.png">

Change Password Input
<img width="320" alt="Screenshot 2020-03-20 at 9 22 39 AM" src="https://user-images.githubusercontent.com/26546816/77146911-7343a480-6a8c-11ea-866f-5610a0356e71.png">

**Comment by Prahitha** [comment]
I would like to work on this issue. Thanks.

**Comment by Paarmita** [comment]
@Prahitha Sure. Just start a PR with the basic input UI for this

![sdvf](https://user-images.githubusercontent.com/26546816/77467211-de360800-6e0b-11ea-971a-3dcf24502069.PNG)

And then I could help you to add other inputs that we need in the UIkit.

**Comment by Meghana-12** [comment]
I would like to work on this issue too as prahitha and I belong to the same team. Thanks.

**Comment by Paarmita** [comment]
@Meghana-12 You can add the search input box in the same way 
https://user-images.githubusercontent.com/26546816/77146791-2e1f7280-6a8c-11ea-8f3f-91bbb03ac6a4.png

**Comment by Meghana-12** [comment]
Sure, thank you.

**Comment by divyanshu-rawat** [comment]
@Meghana-12 @Prahitha Would you like to work on other inputs from this issue?

**Comment by Meghana-12** [comment]
I would like to continue working on this!

**Comment by Paarmita** [comment]
@Meghana-12 That's great, you can take up this input UI with an icon 
https://user-images.githubusercontent.com/26546816/77146796-2fe93600-6a8c-11ea-8fdb-80615842c782.png

**Comment by Paarmita** [comment]
@Prahitha You can take up this input 
Make sure you see the input with the icon on the right and make this accordingly.

<img width="800" alt="Screenshot 2020-04-07 at 12 14 54 AM" src="https://user-images.githubusercontent.com/26546816/78610309-db540200-7864-11ea-9914-c4490bedcbf3.png">
