### ISSUE TITLE
Add icons: Notification, Profile, Search Icons

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#663]
Add the mentioned icons similar to the ones here 
https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons

We are using Material Rounded icons, anyways take SVG icons from here
Notification Icon- 
https://material.io/resources/icons/?search=Notification&icon=notifications&style=round
Profile- https://material.io/resources/icons/?search=Profil&icon=account_circle&style=round
Search Icon- https://material.io/resources/icons/?search=search&icon=search&style=round

**Comment by Paarmita** [comment]
@gargshruti30 @AnjaliGarg13 Let me know who wants to take up this issue.

**Comment by AnjaliGarg13** [comment]
@Paarmita I'll take up this issue.
