### ISSUE TITLE
Add icons: Location, Clear, Create

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#664]
Add the mentioned icons similar to the ones here 
https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons

We are using Material Rounded icons, anyways take SVG icons from here
Location Icon- 
https://material.io/resources/icons/?search=location&icon=location_on&style=round
Clear Icon- https://material.io/resources/icons/?icon=clear&style=round
Create Icon- https://material.io/resources/icons/?icon=create&style=round

**Comment by gargshruti30** [comment]
@Paarmita 
I would like to work on this issue.

**Comment by gargshruti30** [comment]
@divyanshu-rawat @Paarmita do we have to create a branch from master or develop?

**Comment by gittysachin** [comment]
@gargshruti30 you need to create a branch from `develop`.

**Comment by divyanshu-rawat** [comment]
`Develop`
