### ISSUE TITLE
Signup flow Progress Bar UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#668]
**Describe the solution you'd like**
Implementation of the attached Progress bar based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Molecules](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

![Capture](https://user-images.githubusercontent.com/26546816/77455063-ade56e00-6df9-11ea-9433-3f57bf2664e9.PNG)

Put the animations for going from one step to other. Taking reference of UI
 
![loan-application-ui](https://user-images.githubusercontent.com/26546816/77455430-20eee480-6dfa-11ea-86ef-627120f8cd20.gif)

**Comment by siddhishree** [comment]
I'd like to work on this issue.

**Comment by dibakar95** [comment]
Hi. I'm a participant of GSSoC20. And a member of Ignitus-client Slack Channel. I am a react enthusiast.  And I would like to take upon this issue.

**Comment by aditianshu** [comment]
Hi, @Paarmita would like to work on this issue, GSSoC '20 participant, I have prior experience in React. 
Thank You.

**Comment by divyanshu-rawat** [comment]
Hey 👋  Siddhi are you still working on this issue? Hey Dibakar lets wait until Siddhi replies,  Hey aditi sorry please pick up another issue until Dibakar & Siddhi are working on it. If they both will not work they I will be happy to assign it to you :)

**Comment by siddhishree** [comment]
Hey @divyanshu-rawat, I couldn't start working because I didn't get any confirmation from the mentor. However, I'll start working now if I am assigned the issue.

**Comment by divyanshu-rawat** [comment]
@siddhishree Please go ahead 👍
