### ISSUE TITLE
Dashboard: Scroll Bar UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#671]
**Describe the solution you'd like**
Implementation of the attached Scrollbar UI based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Molecules](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

![dsds](https://user-images.githubusercontent.com/26546816/77458187-146c8b00-6dfe-11ea-80a7-e96868d2ec93.PNG)

**Comment by yj2303** [comment]
I would like to fix this issue. Please assign it to me!

**Comment by Paarmita** [comment]
@yj2303 Sure go for it.

**Comment by Dishebh** [comment]
@Paarmita I would like to work on the issue.

**Comment by Dishebh** [comment]
@Paarmita I guess the issue can be closed now.

**Comment by divyanshu-rawat** [comment]
sure @Dishebh :)
