### ISSUE TITLE
Dashboard: Opportunities saved UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#672]
**Describe the solution you'd like**
Implementation of the attached Opportunities saved UI based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Layouts](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route. For the individual Card add them in a Card layout under [Organisms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms) and then create a grid in the Layout section.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

You can view the [Opportunity Listing UI ](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList) for reference.

![fdbdb](https://user-images.githubusercontent.com/26546816/77459109-7ed1fb00-6dff-11ea-9e04-f7993c166f5e.PNG)

**Comment by Paarmita** [comment]
@arpita-in I have assigned you Tags issue, it would be great if you could provide a PR for that and then take up this one.

**Comment by arpita-in** [comment]
No problem @Paarmita .. I will make PR then I will come to this

**Comment by abhu-A-J** [comment]
@Paarmita Can I try this, if the issue is free to take??

**Comment by divyanshu-rawat** [comment]
@abhu-A-J this is only for RGSOC 2020 applicants thanks :) 🙏

**Comment by abhu-A-J** [comment]
> @abhu-A-J this is only for RGSOC 2020 applicants thanks :) 🙏

Oh okay!!! Not a problem ! :)

**Comment by Prahitha** [comment]
I would like to work in this issue. Thanks

**Comment by Paarmita** [comment]
@Prahitha Sure

**Comment by Paarmita** [comment]
@Prahitha You need to make this kind of card with title, subtitle, and description.

<img width="445" alt="Screenshot 2020-03-26 at 4 17 07 PM" src="https://user-images.githubusercontent.com/26546816/77663538-74d60680-6f7d-11ea-9001-541386fa116a.png">
