### ISSUE TITLE
Change shadow of Navbar

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#675]
**Is your feature request related to a problem? Please describe.**
White navbar shadow is too dark.

**Describe the solution you'd like**
Put the shadow to `box-shadow: rgba(0, 0, 0, 0.05) 0px 2px 4px 0px;`

<img width="1440" alt="Screenshot 2020-03-24 at 10 57 00 PM" src="https://user-images.githubusercontent.com/26546816/77480868-cb7afd80-6e22-11ea-9871-81317da02905.png">

**Comment by HarshiniKarumuri** [comment]
I would like to work on this issue. Is this a part of RGSoC?

**Comment by Paarmita** [comment]
@HarshiniKarumuri This already has been resolved in migration PR. You can take up another issue.
