### ISSUE TITLE
Dashboard: Button with icon

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#676]
**Describe the solution you'd like**
Implementation of the attached Button with icon component based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Atoms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms)->Buttons->Buttons with icons which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

As a user I could provide the text and icon as props and use the button wherever possible. 
You can see this button for reference to develop it. 
https://github.com/Ignitus/Ignitus-client/blob/0bdd1849a885db683fcb44d829d8c5163fb3ff91/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/Components/OppurtunityList.tsx#L37

You need to develop the buttons with all the 5 colors which is already there
![vfdvd](https://user-images.githubusercontent.com/26546816/77467784-e2165a00-6e0c-11ea-9475-0da7bc583459.PNG)

**Comment by yj2303** [comment]
I would like to fix up this issue . Kindly assign it to me.

**Comment by Paarmita** [comment]
@yj2303 Sutre, go for it.

**Comment by Dishebh** [comment]
I guess this issue is resolved now.

**Comment by Paarmita** [comment]
No, there is an option for adding the icon on the right of the text, but the logic needs to be solved for the icon on left in the button.

**Comment by Dishebh** [comment]
@Paarmita can I work on this?

**Comment by Paarmita** [comment]
Sure @Dishebh

**Comment by Dishebh** [comment]
@Paarmita there are already some buttons that have icons on their right (as you mentioned) in the `/interface/Buttons` route, and so what I have to do is to add some buttons that should have the icons on their left as well, and in the same path i.e, `interface/Buttons`. 

Please correct me here if I am wrong.

**Comment by Paarmita** [comment]
Yes @Dishebh, you understand that right.

**Comment by Dishebh** [comment]
Done✔️. @Paarmita can you please add the gssoc labels to the PR as well?
