### ISSUE TITLE
FORK/RUN/SUGGEST

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#68]
Fork the Ignitus repository and run it locally, improve something on it and then send the PR for the same, or suggest something to us that we can improve, you can also star it if you like what we are doing 👍

**Comment by TashaPenwellHC** [comment]
I can give this one a go.  May open it up to students this afternoon for suggestions as well.

**Comment by divyanshu-rawat** [comment]
@TashaPenwellHC  great 👍
