### ISSUE TITLE
Overlay screen on Logout UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#682]
**Describe the solution you'd like**
Implementation of the attached logout overlay message UI based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Layouts](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout) which is displayed in the [ignitus-UserInterfaceKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route. This should be similar to Not found or under construction components. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

This overlay should be tbe displayed no longer than 600ms (0.6s), then disappears to go back to the main sign in page. The browser should be able to memorize which sign in page (student or professor) the user has gone through to save them from the hassle of clicking more links than needed.

<img width="456" alt="Screenshot 2020-03-25 at 4 02 52 PM" src="https://user-images.githubusercontent.com/26546816/77551411-9a4a0e00-6eb2-11ea-9a2b-4b55204744f2.png">

**Comment by nooras** [comment]
Hello @Paarmita  I am student of GSSOC . Can i do this ?? Will you assing it to me ??Thanks

**Comment by Dishebh** [comment]
@Paarmita I guess the issue can be closed now :)

**Comment by Dishebh** [comment]
@divyanshu-rawat this too

**Comment by Dishebh** [comment]
Closing it via #872
