### ISSUE TITLE
Dashboard: Separator UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#684]
**Describe the solution you'd like**
Implementation of the attached Separator with text UI based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Atoms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms) which is displayed in the [ignitus-UserInterfaceKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route (http://www.ignitus.org/interface). 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

Create a line hr component and then add a text between it.

<img width="451" alt="Screenshot 2020-03-25 at 4 39 30 PM" src="https://user-images.githubusercontent.com/26546816/77555352-7210de00-6eb7-11ea-8edb-4b1c4a088432.png">

**Comment by Meghana-12** [comment]
I would like to work on this.
