### ISSUE TITLE
Add Interface link in Footer

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#695]
As we have UI kit under` /interface`, so I suggest we need to have a link to it in the footer under **Links** section.

And the new order will be 

> Home, About Us, Design System, Contributors

![sdgde](https://user-images.githubusercontent.com/26546816/77737649-afd44a80-700e-11ea-8edd-55103855044a.PNG)

**Comment by Adyasha8105** [comment]
I want to work on this issue @Paarmita

**Comment by Adyasha8105** [comment]
Is this for GSsoc participants?

**Comment by Paarmita** [comment]
@Adyasha8105 You can take thi

**Comment by Adyasha8105** [comment]
@Paarmita Could you point me?

**Comment by Paarmita** [comment]
I didn't got you.

**Comment by Adyasha8105** [comment]
> I didn't get you.

sorry, my mistake. I couldn't able to find the /interface. Now I got it.

**Comment by Adyasha8105** [comment]
If I am getting it right, you want to remove "what we provide?" from the link section in footer?

**Comment by Adyasha8105** [comment]
@Paarmita Can you check my PR?

**Comment by Adyasha8105** [comment]
@divyanshu-rawat  Can you update my scorecard as the issue #695 was already merged?

**Comment by divyanshu-rawat** [comment]
@Adyasha8105 I have added labels to you PR, `gsoc` should grab your score from the labels.

**Comment by Adyasha8105** [comment]
@divyanshu-rawat Okay :)
