### ISSUE TITLE
Remove Prop-Types ★

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#709]
Just search for prop-types in the code base & keep removing it occurrence as we are migrating to typescript we don't to make use of prop-Types anymore.

You can even a send a PR by removing it in any one of the the file. 🎯

**Comment by shreyakapoor08** [comment]
@divyanshu-rawat can I work on this?

**Comment by prangya244** [comment]
I would like to take up the issue.

**Comment by divyanshu-rawat** [comment]
hey @prangya244 , @shreyakapoor08 you both can work on removing prop-Types from different components, before starting please write here in which Component are you removing it, so that there won't be merge conflicts.

**Comment by shreyakapoor08** [comment]
> hey @prangya244 , @shreyakapoor08 you both can work on removing prop-Types from different components, before starting please write here in which Component are you removing it, so that there won't be merge conflicts.

I will remove it from 
1.  team.tsx
2. Login.jsx
3. SignUp.tsx
4. JobConfirmation.jsx
5. dashBoardHeader.js

**Comment by shreyakapoor08** [comment]
@divyanshu-rawat Should I remove it from the rest of the files too ?

**Comment by divyanshu-rawat** [comment]
@shreyakapoor08 They are all removed I removed remaining, please pick up something else if you want to, nevertheless thanks for your interest. 😊
