### ISSUE TITLE
Student Signup: ambiguous invalid email message

### ISSUE THREAD

**Issue by Marvin9** [Ignitus/Ignitus-client#719]
**Describe the bug**
Invalid email message sticking unnecessarily. 

**To Reproduce**
1. Go to [Student Signup](http://www.ignitus.org/signup/student)
![issue_ignitus](https://user-images.githubusercontent.com/17699717/77984561-80378200-732f-11ea-9f61-0029d4ed9316.gif)

**Expected behaviour**
There should not be invalid email message if not obligatory.

**Comment by ashishnagpal2498** [comment]
Hi , can I work on this issue.

**Comment by Marvin9** [comment]
@ashishnagpal2498 Are you working on it?

**Comment by ashishnagpal2498** [comment]
Yes @Marvin9 I am working , sorry for delay.

**Comment by Marvin9** [comment]
Fixes #745
