### ISSUE TITLE
Client side validation in Login and Registration form

### ISSUE THREAD

**Issue by outsourcegb** [Ignitus/Ignitus-client#72]
**Is your feature request related to a problem? Please describe.**
Suggestion wanted to validation in login and registrations forms.  

**Describe the solution you'd like**
Currently we are not using any validation at client side. We can  check what we can include there so that when user (student / professor) fills the form, any error can be prompt instantly or when submit is clicked.

**Describe alternatives you've considered**
There are couple or validation libraries but still lets check what is best for us. 

**Additional context**

**Comment by Paarmita** [comment]
@outsourcegb You can check #64 as this issue looks similar to this 👍

**Comment by LazzyGuy** [comment]
@divyanshu-rawat I would like to check this out any suggestions on libraries

**Comment by LazzyGuy** [comment]
I think there is no need for a library if the task is to only validate signup forms but still, we can use parsleyjs [http://parsleyjs.org/](url)  it depends on jQuery but it's already included in the project.

**Comment by outsourcegb** [comment]
Ok, checkout if its suitable for other forms and we can use it.

**Comment by agoiabel** [comment]
@LazzyGuy @outsourcegb , I could create a sample custom validation for just the login, then you could follow that format to work on sign up.

I think we should not use an external library for this.

**Comment by divyanshu-rawat** [comment]
@agoiabel I also think that we should not use any library for this 👍

**Comment by 9snehal** [comment]
Is the issue still open? I want to work on this issue

**Comment by 9snehal** [comment]
@divyanshu-rawat Is the issue still open? I would like to work on this issue

**Comment by Paarmita** [comment]
Hey @9snehal, validation is done for the login you can work on the signup similar to which @agoiabel has worked upon.
