### ISSUE TITLE
Error in creating files while cloning

### ISSUE THREAD

**Issue by quinnbee** [Ignitus/Ignitus-client#731]
**Describe the bug**
While **cloning the repo** using **MINGW64 (Git Bash)** or **Cygwin**, an error appears stating that the files in src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/Components cannot be created.
**To Reproduce**
1. Git Bash on the directory you want to clone or create a directory.
2. Use command 
```
git clone https://github.com/quinnbee/Ignitus-client.git
```

**Expected behaviour**
```
Cloning into 'Ignitus-client'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (55/55), done.
                                                                                                                             Receiving objects: 100% (10520/10520), 9.86 MiB | 77.00 KiB/s, done.
Resolving deltas: 100% (5801/5801), done.
error: unable to create file src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/Components /index.ts: No such file or directory
error: unable to create file src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/Components /interfaceSeparator.tsx: No such file or directory
Updating files: 100% (495/495), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 -Shell: Git Bash/Cygwin

**Additional context**
**While trying to resolve the issue, I found out that the git checkout breaks when it encounters a file or folder name with space and the folder name Components contains a space in it.** 
I referred the following links:
1. https://github.com/data-8/interact/issues/4
2. https://stackoverflow.com/questions/52088872/git-pull-if-folder-in-remote-contains-spaces
3. https://stackoverflow.com/questions/5999507/mingw-make-cant-handle-spaces-in-path#5999667
4. https://stackoverflow.com/questions/42757759/git-windows-cannot-clone-checkout-repository-paths-with-spaces

**Comment by yj2303** [comment]
Have a look at https://github.com/t-b/git-pre-commit-hook-windows-filenames .

**Comment by quinnbee** [comment]
> Have a look at https://github.com/t-b/git-pre-commit-hook-windows-filenames .

This didn't help.

**Comment by yj2303** [comment]
Check git checkout -f HEAD
Hope, it will help you.

**Comment by quinnbee** [comment]
> Check git checkout -f HEAD
> Hope, it will help you.

The issue is with the folder name Components having a space and hence, git checkout breaks. The issue arises out of error in creation of files under Components, not with git checkout.The maintainers just need to rename it without space. Also, -f is usually not advised. Thanks! :)

**Comment by divyanshu-rawat** [comment]
@shreyakapoor08 this might be something you were also encountering :)

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 this might be something you were also encountering :)
Ohh yess :)🙈

**Comment by divyanshu-rawat** [comment]
@shreyakapoor08  , @quinnbee  I am working on it :)

**Comment by quinnbee** [comment]
> @shreyakapoor08 , @quinnbee I am working on it :)

Thank you! :)

**Comment by divyanshu-rawat** [comment]
it should be fixes please give it a try, @shreyakapoor08 , @quinnbee.

**Comment by divyanshu-rawat** [comment]
> Check git checkout -f HEAD
> Hope, it will help you.

hey, thanks for the inputs, If you are using mac/linux it won't be a problem for you, if it windows & running fine for you then you can let us know your solution to the problem :)
