### ISSUE TITLE
DropDown z-index in opportunity filters 🔨

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#740]
**Describe the bug**
I just refactored #723 , durning refactoring I removed presence of css property position, which we avoid to use, so removing it causes z-index to not work properly.

**To Reproduce**
You can check the behaviour here.
https://deploy-preview-710--peaceful-nightingale-55a1b7.netlify.com/interface/opportunityPosted

**Expected behaviour**
Expected behaviour is to not increase the height of flex container, instead using z-index over the container encapsulating the entire opportunity content.

**Screenshots**
![filters](https://user-images.githubusercontent.com/13464678/78506215-5e4b5e80-7778-11ea-910e-8b3430db4a81.gif)

**Additional context**
It would be great if we can achieve this without replying on position property of css, some references that show how we can use z-index with flex without setting position property. 

https://stackoverflow.com/questions/45398088/z-index-doesnt-work-with-flex-elements
https://www.freecodecamp.org/forum/t/z-index-isnt-working-in-flexbox/183591

**Comment by nooras** [comment]
Hello @divyanshu-rawat  Can I work on this ??

**Comment by Dishebh** [comment]
@divyanshu-rawat I would like to work on the issue.

**Comment by Dishebh** [comment]
@divyanshu-rawat shouldn't adding a height to the container solve the issue? I tried the links you mentioned above, but did not get any fruitful results. Maybe we should try fixing the height using max-height on hover state, or maybe even assigning a height to the whole container so it won't overlow?
