### ISSUE TITLE
Dashboard: Profile detail view

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#743]
**Describe the solution you'd like**
Implementation of the attached Profile detail section UI based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This Section will be viewed on profile. Please try to use the components from the existing design system. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

<img width="449" alt="Screenshot 2020-04-06 at 1 35 15 PM" src="https://user-images.githubusercontent.com/26546816/78554617-c5feb980-780b-11ea-9604-faf203571fb8.png">

**Comment by divyanshu-rawat** [comment]
@Meghana-12 Would you like to work on it?

**Comment by Meghana-12** [comment]
sure!

**Comment by Meghana-12** [comment]
where should this be added?

**Comment by Paarmita** [comment]
@Meghana-12 Create a different route `/profile` and add this section.

**Comment by Paarmita** [comment]
Fixed
