### ISSUE TITLE
White space on right side of screen in mobile version

### ISSUE THREAD

**Issue by parsa-webdev** [Ignitus/Ignitus-client#746]
On the mobile version, there's unwanted white space on the right side of screen, which is preventing content to be 100% of screen width.

This starts to occur if the screen size in less than 400 pixels.
This problem has been seen only on the Homepage so far.

![issue](https://user-images.githubusercontent.com/60968775/78564176-dc256d80-783d-11ea-82e6-6e47f167dd28.png)

**Comment by parsa-webdev** [comment]
This may work. Changing the font size of the intro text (Welcome To Ignitus) from 78px to 60px or lower seems to fix the issue. 

![fontSize](https://user-images.githubusercontent.com/60968775/78968693-0d948680-7b27-11ea-9793-5e9a44107766.png)

**Comment by Paarmita** [comment]
@parsa-webdev Thanks a lot for your suggestions, but I am planning to change the layout of the hero section to some simpler UI, so this issue won't be there now.

**Comment by parsa-webdev** [comment]
That would be great, thanks!
