### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Sapna2001** [Ignitus/Ignitus-client#750]
Readme can be updated with details of mentors,admins,slack channels and details of gssoc. Please assign me this issue.

**Comment by Marvin9** [comment]
You can still create pull request.

**Comment by divyanshu-rawat** [comment]
@Sapna2001 I think issue is not relevant, Ignitus is not only participating in GSSOC.
Nevertheless, its an open-source project so there are no fixed mentors here, only contributors & maintainers, who are doing their job well by reviewing the pull requests.
