### ISSUE TITLE
Text area not expanding as we type in 🤷‍♀️

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#754]
**Describe the bug**
The text area in the Multimedia input UI is not increasing automatically as the user types in. 

**Expected behavior**
There could be 2 possible solutions for this-
Either add a scrollbar in the textarea itself or increase the text area size automatically and simultaneously decreasing the fon-size(like in Facebook post)

**Screenshots**
<img width="776" alt="Screenshot 2020-04-08 at 5 38 27 PM" src="https://user-images.githubusercontent.com/26546816/78803848-c6d84c80-79bf-11ea-86b7-b3ea891c1fc5.png">

**Comment by Marvin9** [comment]
Is it necessary to decrease font size on increment of text area size?

**Comment by divyanshu-rawat** [comment]
I think it may have performance effects of we do something like that?
I believe listeners should be involved in doing so?

**Comment by Marvin9** [comment]
Yes, ```onChange``` is involved. We need to check each time whether height is increased or decreased and set font size accordingly. It is also required to bound minimum and maximum font size.

Second approach works fine without decreasing the font.

![multimedia](https://user-images.githubusercontent.com/17699717/78913270-65d77400-7aa6-11ea-8954-8b3ab2dfdee0.gif)

**Comment by Paarmita** [comment]
@Marvin9 According to user experience, we should not increase the height of the box this much, we should limit to some height and accordingly decrease the font-size to adjust that height, also look smooth to the user. 

Let's say, if the user entered the paragraph of the full page height, then this box will keep on increasing, which is bad user experience.

**Comment by Marvin9** [comment]
Ook @Paarmita 
Can you give some more reference? So I can try further.

**Comment by Marvin9** [comment]
Fix #763
