### ISSUE TITLE
Bug in login/sign up screen

### ISSUE THREAD

**Issue by ashishnagpal2498** [Ignitus/Ignitus-client#757]
**Alert messages**
The alert messages , invalidEmail , password Mismatch , User not found Field empty persist even If the fields are correct or not yet filled as error was in previous case. 

**To Reproduce**
1. Go to 'sign in 'page. Try to sign in with student account. Account should not exist.
2. Click on 'Signup' . The error is shown as user is not found.
3. Go to SignUp screen and create a student account.
4. Go back to sign in screen , the error persist.

Same behavior is seen at different places.

**Expected behaviour**
The errors should be cleared.

**Screenshots**
![image](https://user-images.githubusercontent.com/36301481/78880126-8b4a8a80-7a72-11ea-9ecb-31181e43df11.png)

Multiple Errors -
![image](https://user-images.githubusercontent.com/36301481/78880144-956c8900-7a72-11ea-8de1-06973469edab.png)

I want to correct these issues and work as part of GSSOC 20.

**Comment by divyanshu-rawat** [comment]
This is clearly a bug, I was planning to open an issue for it since long time.

**Comment by Marvin9** [comment]
This issue should be given priority. Also please check if there is any other side effects.

**Comment by ashishnagpal2498** [comment]
I can work on this.

**Comment by Marvin9** [comment]
Thanks @ashishnagpal2498 but as It is priority and you are working on other issues as well, I will take this up.

**Comment by Marvin9** [comment]
Fix #765
