### ISSUE TITLE
CSS minor issue in login/signup screen

### ISSUE THREAD

**Issue by ashishnagpal2498** [Ignitus/Ignitus-client#758]
**Login/SignUp as Student/Professor Card**
When a user hover on the card the scale transition occur on the card but link to the next page only available on the image , even though the cursor is pointer.

**To Reproduce**
1. Go to 'Signup/login'
2. Hover on professor/student card
3. Try to click outside image

**Expected behaviour**
Either card should not have cursor as pointer or whole card should be provided with link to next page.

**Screenshots**
![image](https://user-images.githubusercontent.com/36301481/78880866-a669ca00-7a73-11ea-9969-2918938b97bf.png)

**Comment by divyanshu-rawat** [comment]
Thanks for opening this up @ashishnagpal2498 👍 , let me know if you want to fix this.

**Comment by ashishnagpal2498** [comment]
Yes , I want to fix this.

**Comment by ashishnagpal2498** [comment]
No GSSOC label ?
