### ISSUE TITLE
CSS Improvement in our team cards

### ISSUE THREAD

**Issue by ashishnagpal2498** [Ignitus/Ignitus-client#759]
**CSS Issue**
1) Card overlaps on hover
2) Abrupt Links display on hover

**Expected behaviour**
1) margin should be increased between the cards.
2) Instead of display - opacity or visibility will look better I think.

**Screenshot**
![image](https://user-images.githubusercontent.com/36301481/78882076-45db8c80-7a75-11ea-8610-25da06228753.png)

**Comment by divyanshu-rawat** [comment]
I think it needs discussion 👍  cc - @Paarmita , @gittysachin , @Marvin9

**Comment by Paarmita** [comment]
@ashishnagpal2498 We have aligned this by considering the width of the card, font and other factors and I think the current UI looks fine to me for now. 
Nevertheless, on the mobile view, we can remove the hover and show the icons on the cards, because hover does not make sense in small screens.

**Comment by ashishnagpal2498** [comment]
Yes I agree, mobile view and hover doesn't make any sense. So icons should be displayed.
But in desktop view when you hover, do you see a text takes few seconds to get stable, its bit blurry for minimal seconds. Also what are your view on changing that icons to opacity instead of display ?. As card is scaling and also the content in transforming in Y direction due to icons.

**Comment by Marvin9** [comment]
Overlapping is not issue as far as any content is not hidden because of it. Design also looks fine.
 
However I noticed if we hover on any card in 2nd row, It seems like the card above is still on the top of hovered one. 

Any thoughts on removing hover effect? @divyanshu-rawat @Paarmita

**Comment by Paarmita** [comment]
Then, we can completely get rid of the hover effect and add the icons in the card itself.

**Comment by Marvin9** [comment]
@ashishnagpal2498 Can you fix that?

**Comment by ashishnagpal2498** [comment]
Ya sure.
