### ISSUE TITLE
Minor issue in Header nav

### ISSUE THREAD

**Issue by ashishnagpal2498** [Ignitus/Ignitus-client#760]
**Description**
The navbar automatically gets open initially when I switch from desktop to mobile view.

**To Reproduce**
1. Change the view to responsive

**Screenshot**
![image](https://user-images.githubusercontent.com/36301481/78882641-f77abd80-7a75-11ea-94a6-9cf1691d0007.png)

**Comment by divyanshu-rawat** [comment]
Thanks for opening this up @ashishnagpal2498 👍

**Comment by ashishnagpal2498** [comment]
Yeah sure.
