### ISSUE TITLE
Getting rid of default exports 💡

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#761]
**Is your feature request related to a problem? Please describe.**
Currently we are exporting some components as `default` & some components as `const`.

**Describe the solution you'd like**
Now we plant to completely get rid of default export at all, reason being are stated in the blog attached in additional context.

**Describe alternatives you've considered**
N.A

**Additional context**
https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad

**Comment by divyanshu-rawat** [comment]
I will soon create a PR for some components then anyone who is willing to take up this issue can follow the same process. cc - @Paarmita , @gittysachin , @Marvin9

**Comment by divyanshu-rawat** [comment]
To ensure better `dev` experience if we are exporting a single component out of directory then we will name the file that is exporting the component as `index.tsx` instead of naming it as a name of the component.

**Comment by Marvin9** [comment]
Agreed.
What should be our approach on components with error boundries? Should be stick with ```export default``` there?

**Comment by divyanshu-rawat** [comment]
example of `exporting const with HOC.`

I am updating the PR.

```

import React from 'react';
import {Link} from 'react-router-dom';
import {Container, Paragraph, TopSection, BottomSection} from '../styles';
import {Button} from '../../../ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/buttons';
import {withErrorBoundary} from '../../../ignitus-Shared/ignitus-ErrorHandlingComponents/errorBoundary';

export const GetStarted: React.FunctionComponent = withErrorBoundary(() => (
  <Container>
    <TopSection>
      <Paragraph>
        Get started for free - join thousands of students and researchers
        already using Ignitus to share their knowledge, work together, and get
        amazing opportunites.
      </Paragraph>
    </TopSection>
    <BottomSection>
      <Link to="/Signup">
        <Button category="orange" size="large">
          Sign-Up
        </Button>
      </Link>
    </BottomSection>
  </Container>
));

```

**Comment by divyanshu-rawat** [comment]
We will be exporting everything as `const`. what do you say @Marvin9 ?

**Comment by divyanshu-rawat** [comment]
I am also deleting selectors, sagas, actionTypes in those file that will never be calling any server endpoint, I will pushing major cleanup in develop soon.

**Comment by Marvin9** [comment]
I strongly agree with migration to ```export const```.

**Comment by divyanshu-rawat** [comment]
Great 👍

**Comment by divyanshu-rawat** [comment]
export const along with `index.tsx/index-ts` inside `Components` directory, I will be sending PR soon for some components.

**Comment by Marvin9** [comment]
Sure. Do we need migrate slowly? Or in one PR.

**Comment by divyanshu-rawat** [comment]
I will migrate some then you can pick up some :)

**Comment by Marvin9** [comment]
@divyanshu-rawat 

By wrapping component in ```withErrorBoundry```, props definitions are being untracked.

```javascript
export const Login: React.FC<LogInProps> = withErrorBoundary(({ logInRequest, studentLoginData, clearPreviousLogin }) => {
```

Solution could be

```javascript
export const Login: React.FC = withErrorBoundary(({ logInRequest, studentLoginData, clearPreviousLogin }: LogInProps) => {
```
However I think It will become cluttered. What do you think?

**Comment by divyanshu-rawat** [comment]
@Marvin9 So it is the question of code readability right ? or props definitions are being untracked are causing any trouble to typescript complier.

**Comment by Marvin9** [comment]
Code readability. I would prefer components defined as ```Component: React.FC<Props>```

**Comment by Paarmita** [comment]
Changed all default exports to constants

**Comment by Dishebh** [comment]
@divyanshu-rawat can I take up the issue, if it is available under gssoc?
