### ISSUE TITLE
Get rid of the console warnings

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#768]
**Describe the bug**
There are some console warnings that pop up while running the project locally.

**Expected behaviour**
There should no warnings on running the project.

**Screenshots**
![Screenshot from 2020-04-10 21-57-41](https://user-images.githubusercontent.com/43489708/79006268-6b03f400-7b76-11ea-88bb-e831b94f8be4.png)

**Desktop (please complete the following information):**

**Smart phone (please complete the following information):**

**Additional context**

**Comment by Dishebh** [comment]
Working on it.

**Comment by Marvin9** [comment]
Sure @Dishebh 
Try to reduce them as much as possible.

**Comment by Marvin9** [comment]
Fix #772

**Comment by Marvin9** [comment]
Fix #772
