### ISSUE TITLE
Pushing to PR fails.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#771]
**Describe the bug**
I am getting this err while pushing my changes to any PR.

**Screenshots**
<img width="277" alt="Screenshot 2020-04-10 at 21 05 19" src="https://user-images.githubusercontent.com/13464678/79016393-1a3ccd00-7b6f-11ea-8e3f-68d38914f0c5.png">

**Additional context**
@Marvin9 seems to be caused by recent changes of pr-preview. ? do you have any idea.

**Comment by divyanshu-rawat** [comment]
It would be great if it can be resolved soon then I will merge everything to master as develop has  grown bigger. 😅

**Comment by divyanshu-rawat** [comment]
Just to experiment I deleted the fie in this PR, and then I can push back to `github`. #753

**Comment by divyanshu-rawat** [comment]
closing this the problem is that once you add a workflow you need to refresh tokens of an other git client you are using to take care of git workflow.

**Comment by Marvin9** [comment]
Sorry @divyanshu-rawat , didn't expect that. I saw you already solved 😀 Let's keep an eye on action tab for some time.
