### ISSUE TITLE
Replace Axios => Fetch

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#773]
**Is your feature request related to a problem? Please describe.**
Should we replace our `axios` calls with fetch api?

**Describe the solution you'd like**
As fetch is native to browser, so do we need an additional NPM package like `axios` to communicate to server from client.

**Describe alternatives you've considered**
N.A

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by divyanshu-rawat** [comment]
what do you think @Marvin9 , @abhu-A-J , @Paarmita ? :)

**Comment by Marvin9** [comment]
I read [this article](https://medium.com/@thejasonfile/fetch-vs-axios-js-for-making-http-requests-2b261cdd3af5), I think we should stick with axios.

**Comment by abhu-A-J** [comment]
@divyanshu-rawat I think we can replicate all the features of Axios with fetch. The only reason why I might prefer Axios is for its backward compatibility I guess!
Also sometimes fetch can handle `bad request` a  little weird if you place catch before then Something like this:
```
const url = 'https://jsonplacehoer.typicode.com/todos/1';
fetch(url)
.catch(error => console.log('BAD'))
.then(response => console.log('GOOD'));
```

It's still gonna run `then` block. Axios handles this as well! But it is a minor thing!
I think you should keep `Axios`!
