### ISSUE TITLE
Skeleton UI for dashbaord

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#778]
**Is your feature request related to a problem? Please describe.**
After signup/log in the loader is displayed during the duration request is made.

**Describe the solution you'd like**
As a good user experience, I suggest using a skeleton UI page that will be displayed just after the user clicks the signup/login. And this skeleton will be displayed till the request from the backend is complete and then the data will be loaded.

**Additional context**
You can read more about the skeletons here-  https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a

![Skeleton Dashboard](https://user-images.githubusercontent.com/26546816/82115358-9758f480-9762-11ea-86f5-7c7f73dc213c.png)

**Comment by steric85** [comment]
Can I take this up?

**Comment by Paarmita** [comment]
@steric85 You can try it. But we prefer to not use external packages, as it increases the bundle size of the application. You can try to add rectangles and give them animations using CSS. Ex- https://codepen.io/jordanmsykes/pen/RgPqgV, https://codepen.io/alyseadlard/pen/WGLorb 

Also, do you need the skeleton UI for it? I plan to have a skeleton for the dashboard page.

<img width="400" alt="Screenshot 2020-04-26 at 10 03 21 AM" src="https://user-images.githubusercontent.com/26546816/80301575-319dcc00-87a5-11ea-9a91-480e8ac8d071.png">

**Comment by steric85** [comment]
Sure. Will check out these examples
Yes, I'll be needing a skeleton UI
