### ISSUE TITLE
Convert loader gif of Ignitus into CSS

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#779]
**Is your feature request related to a problem? Please describe.**
Currently, ignitus has 2 loaders in an animated gif format and has some background that does not look good on some backgrounds. 

**Describe the solution you'd like**
I suggest to make the animation in CSS, so the problem of user interface and optimization of the image both are solved.

**Describe alternatives you've considered**
For now, we can remake that animated gifs in animated SVG with a transparent background, as an alternative.

**Additional context**
Loader- 

1. https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Logos/ignitusLoader.gif
2. https://camo.githubusercontent.com/a93c23d55fd294ad3bdafe738bf216506739a3bf/68747470733a2f2f696d6775722e636f6d2f623079363573652e676966

**Comment by aysp-99** [comment]
May I try this? @Paarmita 
Is there any `.svg` file for the logo? I couldn't find one in the repository.

**Comment by Paarmita** [comment]
@aysp-99 There is no animated SVG file for these loaders, for now, I have attached the GIF in the issue for your reference. 
Although, if you need to manipulate the SVG in order to make a CSS animation, I have attached both loaders here. 

1. This is a typical loader example, so you can see some reference examples from codepen.
[loader.svg.zip](https://github.com/Ignitus/Ignitus-client/files/4526890/loader.svg.zip)

2. I think this GIF is easier, as you just need to manipulate the fill property to make this animation. 
[loader2.svg.zip](https://github.com/Ignitus/Ignitus-client/files/4526902/loader2.svg.zip)

Good luck!

**Comment by sharadcodes** [comment]
@Paarmita What about removing the white background and making it transparent ?
