### ISSUE TITLE
Few console errors in Browser due to Styled Component.

### ISSUE THREAD

**Issue by Marvin9** [Ignitus/Ignitus-client#780]
**Describe the bug**
What I understood is, when passing props to styled component, They are forwarded further. However pure HTML Element does not recognize it.

**To Reproduce**
1. Go to 'homepage'
2. Open browser console.
3. Go to ```/interface```
4. Open browser console.

**Expected behaviour**
Clean console.

**Screenshots**
![Screenshot from 2020-04-13 10-16-56](https://user-images.githubusercontent.com/17699717/79093088-c13c8700-7d70-11ea-8c26-1a44c5509676.png)
![Screenshot from 2020-04-13 10-17-25](https://user-images.githubusercontent.com/17699717/79093097-c568a480-7d70-11ea-8459-d5f6449315de.png)

**Desktop (please complete the following information):**
 ~- OS: [e.g. iOS]~
 - Chrome
 ~- Version [e.g. 22]~

**Smartphone (please complete the following information):**
 ~- Device: [e.g. iPhone6]~
 ~- OS: [e.g. iOS8.1]~
 ~- Browser [e.g. stock browser, safari]~
 ~- Version [e.g. 22]~

**Additional context**
Related issue [here](https://github.com/emotion-js/emotion/issues/183)

**Comment by Dishebh** [comment]
@Marvin9 can i work on this?

**Comment by Marvin9** [comment]
Sure @Dishebh

**Comment by Dishebh** [comment]
> Sure @Dishebh

I'm a bit puzzled. The console throws a warning, saying `isexpanded` is not a `boolean` attribute which, contradicts the type saying it is actually a boolean attribute.

**Comment by Dishebh** [comment]
I'm a bit puzzled. The console throws a warning, saying `isexpanded` is not a `boolean` attribute which, contradicts the type saying it is actually a boolean attribute.

**Comment by Marvin9** [comment]
DOM Element attributes only accept strings ```class="xyz"``` if you pass anything but string, It is likely to show error. 

That's why attribute is expecting ```string``` but got boolean ```attr=true``` which is invalid.

**Comment by trblackw** [comment]
@Marvin9 looks like this issue should be closed
