### ISSUE TITLE
Add icons: Slack, Youtube and Medium

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#787]
Add the mentioned icons similar to the ones here 
https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons

Take SVG icons from here
Medium Icon- 
[Monogram.svg.zip](https://github.com/Ignitus/Ignitus-client/files/4479798/Monogram.svg.zip)
Slack Icon- https://brandfolder.com/s/q8tkjq-ekzow-348pqp
Youtube Icon- 
[youtube_monochrome_light_icon.zip](https://github.com/Ignitus/Ignitus-client/files/4479817/youtube_monochrome_light_icon.zip)

**Comment by Dishebh** [comment]
@Paarmita Do we have to replace the font-awesome icons present in the footer with their respective svg icons?

**Comment by Paarmita** [comment]
@Dishebh Yes, we need to but only after this PR gets merged https://github.com/Ignitus/Ignitus-client/pull/789.
