### ISSUE TITLE
Dashboard: Share Overlay UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#791]
**Describe the solution you'd like**
Implementation of the attached Overlay UI based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Molecules](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules) which is displayed in the [ignitus-UserInterfaceBook](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceBook) folder at `/interface` route (http://www.ignitus.org/interface). There is already a Hooray overlay and you should add this similar to that. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly. The social icons are already present in the list. 
- Also the input component is already present, use need to use that https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput

<img width="689" alt="Screenshot 2020-04-16 at 12 16 50 PM" src="https://user-images.githubusercontent.com/26546816/79445121-66a76300-7fdc-11ea-9d02-19db7b5f8da0.png">

**Comment by nandanasreeraj123** [comment]
Can i do this??

**Comment by Paarmita** [comment]
Sure @nandanasreeraj123

**Comment by Dishebh** [comment]
@Paarmita I would like to work on the issue.

**Comment by Paarmita** [comment]
@Dishebh  Sure🙂

**Comment by Dishebh** [comment]
@Paarmita Is there reddit icon in the repo? I couldn't find it.

**Comment by Dishebh** [comment]
![Screenshot from 2020-05-21 17-38-04](https://user-images.githubusercontent.com/43489708/82557730-e7342300-9b89-11ea-83a4-e070238e2e82.png)

@Paarmita is the layout fine? I didn't add the reddit icon because I couldn't find it.

**Comment by Paarmita** [comment]
@Dishebh download the svg icon from flaticon or somewhere else and add the icon. 
Layout looks fine to me for now.

**Comment by tarang75490** [comment]
Mam can i address this issue ??

**Comment by divyanshu-rawat** [comment]
@tarang75490 it already resolved :).
Thanks for your interest :)
