### ISSUE TITLE
Avatar component to get random avatar images from an array

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#796]
Idea is to create a component that will have avatar array and would provide a random avatar PNG image.

Use case: If in future any user didn't add his/her image in the profile, so we can call this component and assign the avatar to that specific profile. Or we can also provide the user option to choose from all these avatars and add that instead of the image. 

We will be using the free avatar generator- https://getavataaars.com/

**Comment by Marvin9** [comment]
I would like to take this up. Is 10 random avatars enough?

**Comment by Paarmita** [comment]
@Marvin9 Cool, we are planning to render these SVG files from GCP, so it would be great if you could create a component from the existing avatars that are already stored in GCP. In the future, I will change these avatars with the new ones. 
Some of the links are here -
```

  'https://storage.googleapis.com/ignitus_assets/ig-avatars/grant.png',
  'https://storage.googleapis.com/ignitus_assets/ig-avatars/melanie.png',
  'https://storage.googleapis.com/ignitus_assets/ig-avatars/george.png',
  'https://storage.googleapis.com/ignitus_assets/ig-avatars/eugene.png
```
