### ISSUE TITLE
TS Types

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#799]
**Is your feature request related to a problem? Please describe.**
Fortunately we are able to migrate entire legacy-code to TS, unfortunately at lot of places types are either missing or are defined as `any`.

**Describe the solution you'd like**
It would be if we step-by-step replace `any` with appropriate `types`, and define types at those place where it is missing.

**Describe alternatives you've considered**
N.A

**Additional context**
Ping me if you struck anywhere while contributing.

**Comment by Dishebh** [comment]
@divyanshu-rawat I guess there is already an issue, having same the purpose. Issue: #530 Please have a look.

**Comment by divyanshu-rawat** [comment]
@Dishebh yes kind of similar, would you like to work on it?
