### ISSUE TITLE
Add icon in header to differentiate student and professor dashboards

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#801]
Presently, in the user dashboard, he/she doesn't see whether it is logged in from Student or Professor. I thought of adding an icon beside the email, to differentiate the 2.

I have added 2 SVG icons with this issue, the idea is to show one for student dashboard and other with Professor(with glasses) on the right of the email in the Header.

You need to check the user role and accordingly add the SVG icon beside the email [here](https://github.com/Ignitus/Ignitus-client/blob/4b73cabb390637748b9132a4c31487c53a5c5d81/src/ignitus-Dashboard/ignitus-DashboardHeader/Components/index.tsx#L38) 

[Profile icons.zip](https://github.com/Ignitus/Ignitus-client/files/4500367/Profile.icons.zip)

<img width="536" alt="Screenshot 2020-04-19 at 11 46 23 PM" src="https://user-images.githubusercontent.com/26546816/79700705-09d7d100-8298-11ea-9908-87a0c215d48e.png">

**Comment by Meghana-12** [comment]
I would like to work on this issue.

**Comment by Paarmita** [comment]
@Meghana-12 What's the progress on this?

**Comment by Meghana-12** [comment]
Sorry for the delay, it's almost done. I'll put up a PR tonight.
