### ISSUE TITLE
After signup/login, change the content in Signup button

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#816]
**Describe the bug**
After the user signup/login in the dashboard, he/she sees the signup button on the main screen.
![1](https://user-images.githubusercontent.com/26546816/80750601-a7e55a00-8b28-11ea-88f4-67117f41d8ad.PNG)
![2](https://user-images.githubusercontent.com/26546816/80750608-a9af1d80-8b28-11ea-8182-c3a0c9075cb9.PNG)

**Expected behavior**
So, the text in the button should change to` Join Us` and should link to the slack channel for now.

**Comment by aditianshu** [comment]
Can I work on this issue? 
I'm a GSSoC participant

**Comment by Paarmita** [comment]
@aditianshu Sure

**Comment by aditianshu** [comment]
@Paarmita , I've done it. 
In the bottom-left corner the link can be seen which it'll open up to. 

![image](https://user-images.githubusercontent.com/55697933/80857973-dd4a8e80-8c73-11ea-8f8c-c3e42cacb585.png)

![image](https://user-images.githubusercontent.com/55697933/80857981-ecc9d780-8c73-11ea-9653-3dd26cddedc0.png)

**Comment by Paarmita** [comment]
@aditianshu Looks perfect! Can you please send a PR for the it.

**Comment by aditianshu** [comment]
@Paarmita Thanks! 
I've made a PR but there's some issue with the checks which I can't figure out.😅
Could you help me with it?

**Comment by Paarmita** [comment]
@aditianshu, I have seen your PR, so wait for @divyanshu-rawat review and he might help you with the checks.

**Comment by aditianshu** [comment]
@Paarmita my GSSoC score doesn't reflect that I've solved it, could you look into it please?

**Comment by divyanshu-rawat** [comment]
@aditianshu should be updated by now :)
