### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by kichloo** [Ignitus/Ignitus-client#827]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
PR template
**Describe alternatives you've considered**

**Additional context**

**Comment by kichloo** [comment]
It can have Medium as the label

**Comment by Paarmita** [comment]
@kichloo I see it is a feature request template. Also, we have a template for PR. https://www.github.com/Ignitus/Ignitus-client/tree/master/.github%2FPULL_REQUEST_TEMPLATE.
