### ISSUE TITLE
Dashboard: Main UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#833]
**Describe the solution you'd like**
Implementation of the attached UI of the Dashboard section based on code guidelines. 
After Login the user will be directed to the dashboard before the below UI is shown, I plan to have a skeleton UI for this screen which will be displayed till the data of the dashboard is loaded.
For skeleton check [issue#778](https://github.com/Ignitus/Ignitus-client/issues/778)

![Skeleton Dashboard](https://user-images.githubusercontent.com/26546816/82115382-af307880-9762-11ea-912a-9fddefbec906.png)

As this issue contains many details, I decided to divide the dashboard screen into parts like this.

![Group 25](https://user-images.githubusercontent.com/26546816/82114999-6b3c7400-9760-11ea-9214-7a6c5a8649fd.png)

For new posts, we have decided the animation similar to Linkedin posts. 
Don't apply the hover effect as shown in the UI for now, just display the cards.
Add this UI under `/ignitus-dashboard` route.

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, required to implement the design.
- Export the png icons from the design.

**Comment by Meghana-12** [comment]
I would like to work on this.
