### ISSUE TITLE
Migration to SSR? 💭

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#844]
Should we render the react components server-side? 
We are not sure but this is just an idea, feel free to write your views in comments.
Currently, comments are being rendered client-side, we are still researching whether we should move to SSR or not?

**Comment by Marvin9** [comment]
```NextJS``` would be good choice for that. But we have to change whole architecture I think.

**Comment by divyanshu-rawat** [comment]
@Marvin9 I think there are several ways we need to transform completely there are easier ways to migrate CRA -> Next is one way, and if you got time do some search you will definitely find some fruitful insights :).
