### ISSUE TITLE
Shift all tests to a single test folder in the root directory? :thought_balloon: 

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#855]
**Is your feature request related to a problem? Please describe.**
Should we shift all the unit tests to a single test directory? That way, it might become easier to locate the tests for a particular component, and it might prove out to be consistent with the current architecture.

**Comment by Dishebh** [comment]
cc: @divyanshu-rawat @Marvin9 @Paarmita

**Comment by divyanshu-rawat** [comment]
@Dishebh good suggestion, but generally convention is to place them in the same dir. where the component is placed. closing this as of now.
