### ISSUE TITLE
Add GitBook as supporter 👋

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#858]
Add GitBook as Ignitus supporter at Ignitus `Supported By section`.
We can make use of this [logo](https://spng.pngfind.com/pngs/s/94-945871_gitbook-logo-hd-png-download.png).

![Screenshot 2020-06-01 at 22 19 11](https://user-images.githubusercontent.com/13464678/83450676-01a5b080-a456-11ea-943e-fa87fab1a344.png)

**Comment by steric85** [comment]
@divyanshu-rawat I've made the changes in #859 . Can you please check?

**Comment by divyanshu-rawat** [comment]
I will have a look soon @steric85 :)
