### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#860]
**Is your feature request related to a problem? Please describe.**
As of now when a PR gets merged, the corresponding issue needs to be closed manually.

**Describe the solution you'd like**
The issue closing process can be automated by adding `Resolves #{issueNumber}` in the PR description. This can be added in the PR template. It might also make the review process easier.

**Comment by Dishebh** [comment]
cc: @divyanshu-rawat @Marvin9 @Paarmita

**Comment by Paarmita** [comment]
Sure @Dishebh . Go ahead
