### ISSUE TITLE
Notification cards and the page UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#867]
**Describe the solution you'd like**
Implementation of the attached Notifications UI based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Organisms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms) 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

<img width="358" alt="Screenshot 2020-06-10 at 10 44 59 AM" src="https://user-images.githubusercontent.com/26546816/84248658-04fe0380-ab0a-11ea-9935-32b1e23b24a4.png">

**Comment by Dishebh** [comment]
@Paarmita I would like to work on this.

**Comment by Dishebh** [comment]
@divyanshu-rawat it can be closed now

**Comment by Dishebh** [comment]
Closing it via #898
