### ISSUE TITLE
Message Cards

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#868]
**Describe the solution you'd like**
Implementation of the attached Notifications UI based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Organisms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms) 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

<img width="467" alt="Screenshot 2020-06-10 at 11 08 06 AM" src="https://user-images.githubusercontent.com/26546816/84249208-c288f680-ab0a-11ea-9e19-80f7eb91da45.png">

These are part of the Message screens.

**Comment by lilicaetano** [comment]
@Paarmita Can I work on this one?
