### ISSUE TITLE
Improvement in tests.

### ISSUE THREAD

**Issue by Marvin9** [Ignitus/Ignitus-client#871]
**Describe the bug**
If you observe, in every test we set value of ```wrapper``` inside ```beforeEach()``` function, however it is never used in first test case (in most of them, it is snapshot test case). Now we have more than 15 test cases, so this unnecessary call could be overhead.

**To Reproduce**
Examples

https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/defaultButtonWithIcon.test.tsx#L17

https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/defaultCheckbox.test.tsx#L11

**Expected behaviour**
Following pattern of most tests, It should not call ```beforeEach()``` in first test case.

~~**Screenshots**~~

~~**Desktop (please complete the following information):**~~

~~**Smartphone (please complete the following information):**~~

**Additional context**

Solution 1(Brute force):
- Set ```counter = 1``` global variable, inside ```beforeEach``` ignore if ```counter``` is 1, increment ```counter``` by one.

```javascript
let counter = 1;
beforeEach(() => {
 if (counter !== 1) { ... }
 counter++;
});
``` 

Solution 2 (Reusable):
- Use your creativity & define one global function/class to reuse across all tests instead of defining ```counter``` & condition every time.

**Comment by Dishebh** [comment]
@Marvin9 Can we try [scoping](https://jestjs.io/docs/en/setup-teardown#scoping) here? We can write a snapshot test case outside the `describe` block and do a `beforeEach` inside `describe`.

**Comment by Marvin9** [comment]
Go ahead @Dishebh

**Comment by Dishebh** [comment]
@Marvin9 opened a PR #895

**Comment by Dishebh** [comment]
@Marvin9 the issue can be closed now :)
