### ISSUE TITLE
Extra white space in About Page in mobile view

### ISSUE THREAD

**Issue by Meghana-12** [Ignitus/Ignitus-client#875]
**Describe the bug**
There is some extra white space in About us Page in mobile view. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to About us page in mobile view
2. Drag to left.
3. You'll see an extra white space to the right.

**Screenshots**
![Screenshot 2020-06-23 at 3 54 24 PM](https://user-images.githubusercontent.com/44519203/85540925-2811d280-b635-11ea-8270-a133eb56e895.png)

**Comment by Meghana-12** [comment]
I would like to fix this.

**Comment by divyanshu-rawat** [comment]
great @Meghana-12 go-ahead 👍
