### ISSUE TITLE
Inline-Checkbox 📦

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#879]
**Describe the bug**
Checkbox here is not displayed in-line http://www.ignitus.org/interface/defaultCheckbox

**To Reproduce**
1. Go to 'http://www.ignitus.org/interface/defaultCheckbox

**Expected behavior**
Should be displayed inline-block 🔨

**Additional context**
Please let me know if you have any Questions regarding this issue we can have a conversation here or on slack. 🚀

**Comment by Dishebh** [comment]
It can be closed now :)
