### ISSUE TITLE
General settings UI 🎨

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#883]
**Is your feature request related to a problem? Please describe.**

**Minimum Requirement:**
Create a new route `/settings` &  implement general user settings UI, you have to implement the part outlined in a black border.
Add route as `private route `so that it can't be accessed without authentication, private routes are listed here https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Routes/ignitus-DashboardRoutes/index.tsx
Create a  new directory `ignitus-DashboardSettings/generalSettings` in `src/ignitus-Dashboard`.
Inside `generalSettings` follow this structure.

<img width="234" alt="Screenshot 2020-06-27 at 12 40 37" src="https://user-images.githubusercontent.com/13464678/85920377-6ac0ee00-b873-11ea-87d3-8eb3f51b11e0.png">

**Great to have:**
Along with the UI also add the side navigation so that page is complete.
Side navigation component can be found here http://www.ignitus.org/interface/sideNavigation

**Describe the solution you'd like**

![Settings General](https://user-images.githubusercontent.com/13464678/85920244-66e09c00-b872-11ea-9899-458a53f17b7e.png)

**Describe alternatives you've considered**
N.A

**Additional context**

Please pick Input component from here http://www.ignitus.org/interface/primaryInput
Please pick button component from buttons in design kit http://www.ignitus.org/interface/buttons
Let me know if you have any Questions 🎯

**Comment by Dishebh** [comment]
Closing it via #891
