### ISSUE TITLE
Add DigitalOcean as supporter.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#884]
Add [DigitalOcean](https://www.digitalocean.com/) as Ignitus supporter at Ignitus Supported By section.
Logo can be found here https://www.digitalocean.com/press/

<img width="933" alt="Screenshot 2020-06-27 at 13 56 53" src="https://user-images.githubusercontent.com/13464678/85921676-14a57800-b87e-11ea-9851-e4f6ccc8c7df.png">

**Comment by daniel-j-davis** [comment]
Hi @divyanshu-rawat, just submitted a PR for this as my first contribution to the code.

**Comment by Dishebh** [comment]
@divyanshu-rawat the issue can be closed now :)
