### ISSUE TITLE
No component displayed under Dashboard in Organisms

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#900]
**Is your feature request related to a problem? Please describe.**
Currently, there is no component displayed at route `/interface/dashboardNavigation`, which can be accessed under Organisms in `Side Navigation/Dashboard`.

**Comment by divyanshu-rawat** [comment]
any insights @Paarmita, @Dishebh thanks for pointing out!.

**Comment by Dishebh** [comment]
@Paarmita can you please help me with what component should come under this route?
