### ISSUE TITLE
Location API 🌍

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#902]
**Is your feature request related to a problem? Please describe.**
Navigate to http://www.ignitus.org/flow/studentSignUpFlow, you will notice here you will be asked for `Country/Region`, `TimeZone ` you can leave province-input as of now we will remove it soon.

Would be great if we can call location API once the user starts typing his/her location.

**Describe the solution you'd like**

![Screenshot 2020-07-20 at 00 56 14](https://user-images.githubusercontent.com/13464678/87887293-f289ba80-ca23-11ea-80cd-75d6c62d7371.png)

**Describe alternatives you've considered**
N.A

**Additional context**
The dropdown should pop-up like in the attached screenshot, once user starts typing the location.
Let me know if you have any Questions :)

**Comment by Dishebh** [comment]
@divyanshu-rawat to use the google maps api here, we would need a google developer's account with billing enabled on it. Please let me know if you know of any other alternatives?

**Comment by amuchand47** [comment]
There are few alternative of Google Map API like **Tom Tom, MapBox , OpenLayers** etc . @divyanshu-rawat @Dishebh

**Comment by divyanshu-rawat** [comment]
@Dishebh , feel free to analyse what @amuchand47 suggested :)
