### ISSUE TITLE
add a messageDetail component in Organisms 

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#908]
**Describe the solution you'd like**
Implementation of the attached `messageDetails` component based on [code guidelines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Organisms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms) which is displayed in the [ignitus-UserInterfaceBook](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceBook) folder at `/interface` route (http://www.ignitus.org/interface). 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=387%3A3) for User-Interface and other styles-related issues.

You can view all the CSS, colours, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern.
You can download SVG icons from the Figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly. The social icons are already present in the list.

![Screenshot from 2020-08-05 13-58-22](https://user-images.githubusercontent.com/43489708/89402055-e300b600-d733-11ea-9cbf-20828445de76.jpg)

Anyone willing to take this issue can ask his/her doubts before taking up either to @Dishebh , @divyanshu-rawat or design related concerns to @Paarmita :)

**Comment by Dishebh** [comment]
@divyanshu-rawat @Paarmita pls see if the above issue is correct, and can be worked upon.

**Comment by divyanshu-rawat** [comment]
@Dishebh looks good to me, anyone willing to take this issue can ask his/her doubts before taking up either to @Dishebh , @divyanshu-rawat or design related concerns to @Paarmita  :)

**Comment by Sasha411** [comment]
I have added some more variables for formatting message.
You can see it here : https://imgur.com/C9EteqC

**Comment by Dishebh** [comment]
@Sasha411 Looks great! But there's already an open PR for it, so you should have asked (or mentioned) before working on the issue. Nevermind, you can still open a PR for it if you have solved the issue :)

**Comment by Sasha411** [comment]
@Dishebh My bad,I am new to this, gonna ask before I work on something.
