### ISSUE TITLE
add a deleteFinal component in Organisms

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#910]
**Describe the solution you'd like**
Implementation of the attached `deleteFinal` component based on [code guidelines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Organisms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms) which is displayed in the [ignitus-UserInterfaceBook](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceBook) folder at `/interface` route (http://www.ignitus.org/interface). 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=536%3A20) for User-Interface and other styles-related issues.

You can view all the CSS, colours, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern.
You can download SVG icons from the Figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly. The social icons are already present in the list.

![Screenshot from 2020-08-05 21-26-26](https://user-images.githubusercontent.com/43489708/89436040-4e15b100-d763-11ea-9955-0dfd313923f7.jpg)

Anyone willing to take this issue can ask his/her doubts before taking up either to @Dishebh, @divyanshu-rawat or design-related concerns to @Paarmita :)

**Comment by divyanshu-rawat** [comment]
Thanks @Dishebh for opening this up, feel free to reach any of us if you are facing problem while working on this issue :)
