### ISSUE TITLE
add a modalApply component under Molecules 

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#919]
**Describe the solution you'd like**
Implementation of the attached `modalApply` component based on [code guidelines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Molecules](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules) which is displayed in the [ignitus-UserInterfaceBook](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceBook) folder at `/interface` route (http://www.ignitus.org/interface). 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=202%3A60) for User-Interface and other styles-related issues.

You can view all the CSS, colours, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern.
You can download SVG icons from the Figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly. The social icons are already present in the list.

![Screenshot from 2020-08-11 20-20-35](https://user-images.githubusercontent.com/43489708/89913236-19956f80-dc11-11ea-8b25-c4daf5c60c8d.jpg)

Anyone willing to take this issue can ask his/her doubts before taking up either to @Dishebh, @divyanshu-rawat or design-related concerns to @Paarmita :)

**Comment by AudreyKj** [comment]
@Dishebh @divyanshu-rawat @Paarmita hello! i'm a first-timer and would love to work on this. is it still available?

**Comment by Dishebh** [comment]
@AudreyKj unfortunately, there's already an open PR for it. You can try out #921 or any other issue that you feel like to work upon :)

**Comment by Dishebh** [comment]
Closing it via #923
