### ISSUE TITLE
add a messageSettings component under Organisms

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#921]
**Describe the solution you'd like**
Implementation of the attached `messageSettings` component based on [code guidelines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Organisms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms) which is displayed in the [ignitus-UserInterfaceBook](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceBook) folder at `/interface` route (http://www.ignitus.org/interface). 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=510%3A36) for User-Interface and other styles-related issues.

You can view all the CSS, colours, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern.
You can download SVG icons from the Figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly. The social icons are already present in the list.

![Screenshot from 2020-08-11 20-59-58](https://user-images.githubusercontent.com/43489708/89917207-2799bf00-dc16-11ea-8df8-b9c0070792cd.jpg)

Anyone willing to take this issue can ask his/her doubts before taking up either to @Dishebh, @divyanshu-rawat or design-related concerns to @Paarmita :)

**Comment by AudreyKj** [comment]
@Dishebh would love to work on this - is it still open?

**Comment by Dishebh** [comment]
Yeah! I will assign this issue to you :)

**Comment by AudreyKj** [comment]
great! will work on it asap :)

**Comment by AudreyKj** [comment]
@Dishebh sorry i won't be able to take care of this, I have too much work!

**Comment by hrahul2605** [comment]
Hey @Dishebh  , can i work on this now?

**Comment by Dishebh** [comment]
Sure :+1:
