### ISSUE TITLE
add a newMessage component under Organisms

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#925]
**Describe the solution you'd like**
Implementation of the attached `newMessage` component based on [code guidelines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Organisms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms) which is displayed in the [ignitus-UserInterfaceBook](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceBook) folder at `/interface` route (http://www.ignitus.org/interface). 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=340%3A2) for User-Interface and other styles-related issues.

You can view all the CSS, colours, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern.
You can download SVG icons from the Figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly. The social icons are already present in the list.

![Screenshot from 2020-08-14 13-45-23](https://user-images.githubusercontent.com/43489708/90229001-cdc31000-de34-11ea-80a4-06d3fce9d69c.jpg)

Anyone willing to take this issue can ask his/her doubts before taking up either to @Dishebh, @divyanshu-rawat or design-related concerns to @Paarmita :)

**Comment by Sasha411** [comment]
I would like to work on this, could you please assign this to me?

**Comment by Dishebh** [comment]
Sure! Go ahead :+1:

**Comment by Sasha411** [comment]
Should I add all the new SVG icons in the icons folder and then import the icons for the new message component or just add icons by using svg tag inside newMessage component under DesignSystem?

Work done till now: https://imgur.com/gallery/473wDZ0

**Comment by Dishebh** [comment]
@Sasha411, add the required icons (in SVG format) in the icons folder and then import them for the `newMessage` component. 

P.S The work looks great up till now!

**Comment by Sasha411** [comment]
I am getting this error when I created new branch from develop and committing changes to develop branch.

husky > pre-commit (node v12.16.3)

> ignitus-client-side-development@5.0.0 ci D:\work\Ignitus new\Ignitus-client
> CI=true react-scripts test && npm run lint

'CI' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ignitus-client-side-development@5.0.0 ci: `CI=true react-scripts test && npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ignitus-client-side-development@5.0.0 ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dreams\AppData\Roaming\npm-cache\_logs\2020-08-16T09_55_08_504Z-debug.log
husky > pre-commit hook failed (add --no-verify to bypass)

**Comment by Dishebh** [comment]
@Sasha411 can you paste a screenshot of the error here? Along with the command you typed

**Comment by Sasha411** [comment]
![image](https://user-images.githubusercontent.com/65828306/90331933-1bc34980-dfd6-11ea-8441-ec2678abd55a.png)

**Comment by Sasha411** [comment]
I think I have to delete CI file which is empty present in root directory

**Comment by Dishebh** [comment]
Try removing the `package-lock.json` file, and deleting the `node_modules`, and then do `npm install` again. See if it fixes the issue.

**Comment by Marvin9** [comment]
@Sasha411 For temporary solution, Inside package.json replace ```CI=true``` => ```set CI=true``` and then commit. (make sure you don't commit package.json)

If that doesn't work. run ```npm run test``` & ```npm run lint```, if there is no error you can commit with ```--no-verify``` flag. I will try to investigate this issue.

**Comment by Sasha411** [comment]
@Dishebh after reinstalling it still didn't worked and @Marvin9  after changin CI=true to set CI=true and not committing package.json I ran npm run test, all test passed but in npm run lint it gives this error:



![npm run lint](https://user-images.githubusercontent.com/65828306/90332536-4794fe00-dfdb-11ea-8030-d3fa21c3838b.png)

**Comment by Marvin9** [comment]
```npm run lint:fix``` to fix lint errors automatically, rest ones you have to fix manually or if not possible then disable eslint for that line.

I wonder how you got so many errors on the first place.

**Comment by Sasha411** [comment]
@Marvin9 So I used `npm run lint:fix` and I am down to 3 errors and 28 warnings.

![image](https://user-images.githubusercontent.com/65828306/90377389-91dab580-e095-11ea-980a-0c967199a2f3.png)

**Comment by Sasha411** [comment]
Just one last thing left can anyone help me with this? No more errors in lint now used verify bypass command to commit that is done last thing is to push changes but question is where?

![image](https://user-images.githubusercontent.com/65828306/90499696-7a6bfd00-e167-11ea-9718-63f33b504d43.png)

**Comment by Dishebh** [comment]
@Sasha411 Push the changes to your origin, not upstream

**Comment by Dishebh** [comment]
`git push origin <branch_name>`

**Comment by Sasha411** [comment]
It gives me this error:

![image](https://user-images.githubusercontent.com/65828306/90503786-a7bba980-e16d-11ea-838c-1d348d08c46a.png)

**Comment by Marvin9** [comment]
Set git origin to forked repo. Your origin should point to this one https://github.com/Sasha411/Ignitus-client.

Then push your updates and make pull request to develop branch.

**Comment by Sasha411** [comment]
@Marvin9  thanks
