### ISSUE TITLE
component opportunitySideCard not listed under Organisms

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#928]
**Describe the bug**
Currently, the component `opportunitySideCard` is not titled under `Organisms` at `/interface` route, though the component is already implemented. 

**To Reproduce**
1. Go to `/interface` route.
2. Under `Organisms`, you won't find any component titled `Opportunity Side Card`

**Expected behaviour**
There should be a component under `Organisms` that is titled `Opportunity Side Card`.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Sasha411** [comment]
Can I work on this please ?

**Comment by Dishebh** [comment]
Sure!
