### ISSUE TITLE
write Unit test for Dashboard Navigation Dropdown component

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#929]
**Describe the solution you'd like**
write Unit test for [`Dashboard Navigation Dropdown`](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-navDropdown) component present under `Atom`. You can view the component at route: `/interface/dashboardNavigationDropdown`.

We are using [enzyme](https://enzymejs.github.io/enzyme/#basic-usage) to test React components and [jest](https://jestjs.io/) to run tests.

Tests references: 
- [defaultButtonWithIcon](https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/index.test.tsx)
- [defaultIconInput](https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.test.tsx)

Make sure to create/update snapshots accordingly. Try to cover as much as possible props twirks of component and edge cases.

**Comment by Marvin9** [comment]
Fixed by #941
