### ISSUE TITLE
write Unit test for modalApply component

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#930]
**Describe the solution you'd like**
write Unit test for [`Modal Apply`](https://github.com/Ignitus/Ignitus-client/tree/develop/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply) component present under `Molecules`. You can view the component at route: `/interface/modalApply`.

We are using [enzyme](https://enzymejs.github.io/enzyme/#basic-usage) to test React components and [jest](https://jestjs.io/) to run tests.

Tests references: 
- [defaultButtonWithIcon](https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/index.test.tsx)
- [defaultIconInput](https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.test.tsx)

Make sure to create/update snapshots accordingly. Try to cover as much as possible props twirks of component and edge cases.

**Comment by upieez** [comment]
hey @Dishebh can I take up this one?

**Comment by Dishebh** [comment]
Sure!
