### ISSUE TITLE
write Unit test for Loader component

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#932]
**Describe the solution you'd like**
write Unit test for [`Loader`](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-Loader/Components) component present under `Atom`. You can view the component at route: `/interface/loader`.

We are using [enzyme](https://enzymejs.github.io/enzyme/#basic-usage) to test React components and [jest](https://jestjs.io/) to run tests.

Tests references: 
- [defaultButtonWithIcon](https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/index.test.tsx)
- [defaultIconInput](https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.test.tsx)

Make sure to create/update snapshots accordingly. Try to cover as much as possible props twirks of component and edge cases.

**Comment by AmanRaj1608** [comment]
I would like to work on this. 
Can you give some more insight on this?

**Comment by Marvin9** [comment]
Updated 👍 

@Dishebh Can you please follow same template in all test issues?

**Comment by Dishebh** [comment]
@upieez, would be great if you could mention here first before starting to work on an issue. Seems like @AmanRaj1608 was also interested in working on it.

**Comment by upieez** [comment]
@Dishebh Oh right so sorry about that I'll take note the next time
