### ISSUE TITLE
redirected to home page when clicked on navbar in smaller resolutions

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-client#940]
**Describe the bug**
Currently, when clicked on navbar in smaller screen resolutions (such as mobile device), we get redirected to the landing page `/`.

**To Reproduce**
1. Go to the `signin` page (for example).
2. Click on the `navbar` in smaller screen resolution devices
3. You will get redirected to the landing page `/`

**Expected behaviour**
You should not get redirected to the landing page if clicked on navbar in small screen sizes.

**Screenshots**
![mobile](https://user-images.githubusercontent.com/43489708/91079567-d5b75700-e661-11ea-884f-b28d67b0007e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RathiJ** [comment]
@Dishebh  ,  Hi ,  I am a beginner , looking for easy good first issue to start contribute.  Shall i fix this ?.

**Comment by Dishebh** [comment]
Sure!

**Comment by abhu-A-J** [comment]
Hi @Dishebh if it's still open I can take up this task?

**Comment by Dishebh** [comment]
@RathiJ, any lead on this?

**Comment by RathiJ** [comment]
@Dishebh  ,  Hi , Thanks for assigning this to me, just now started looking into it .  so far i have seen , the issue is not specific to the small screen, i am seeing the same issue in my laptop chrome browser too.  I went through few folder , i could not find exact html file the site points too. In a brief period of exploring the site, i see  many bugs. 
Since I just started working on it,  if you want this bug has be fixed soon , please feel free to assign it some else too.

**Comment by Dishebh** [comment]
@RathiJ thanks for me briefing me in about this. You can check out some more beginner-friendly issues and may start working on them. Also, feel free to raise issues if you encounter some/any bugs while exploring the project. @abhu-A-J, assigning to you this issue, you can start working on it. :)

**Comment by abhu-A-J** [comment]
> @RathiJ thanks for me briefing me in about this. You can check out some more beginner-friendly issues and may start working on them. Also, feel free to raise issues if you encounter some/any bugs while exploring the project. @abhu-A-J, assigning to you this issue, you can start working on it. :)

Thanks! I'll start working on it!
